version: '3.8' # 使用较新的Compose版本

services:
  gate:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: gserver:latest
    #container_name: dev_gate
    #ports:
    #  - "8080:8080"
    #  - "10001:10001"
    volumes:
      - ./config/gate_1.yaml:/app/config/gate_1.yaml #服务配置文件
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    command: ["-conf=./config/gate_1.yaml"]

  login:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: gserver:latest
    #container_name: dev_login
    volumes:
      - ./config/login_11.yaml:/app/config/login_11.yaml
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    command: ["-conf=./config/login_11.yaml"]
  
  game1:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: gserver:latest
    #container_name: dev_game1
    volumes:
      - ./config/game_101.yaml:/app/config/game_101.yaml
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    command: ["-conf=./config/game_101.yaml"]

  game2:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: gserver:latest
    #container_name: dev_game2
    volumes:
      - ./config/game_102.yaml:/app/config/game_102.yaml
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    command: ["-conf=./config/game_102.yaml"]

  # --- Redis 服务 ---
  redis:
    image: redis:7-alpine # 使用轻量级镜像
    #container_name: my-redis
    #ports:
    #  - "6379:6379"
    network_mode: host
    restart: unless-stopped
    volumes:
      - redis-data:/data/redis # 持久化数据
    command: redis-server --appendonly yes # 启动命令
    # environment:  # 如果需要密码，可以添加
    #   - REDIS_PASSWORD=yourpassword

  # --- MongoDB 服务 ---
  mongodb:
    image: mongo:7
    #container_name: my-mongo
    #ports:
    #  - "27017:27017"
    network_mode: host
    restart: unless-stopped
    volumes:
      - mongo-data:/data/mongodb
    environment:
      # 初始化root用户和密码
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: eat

# 定义持久化卷
volumes:
  redis-data:
  mongo-data:
