// Code generated by proto_parser. DO NOT EDIT.
// 对应的proto规范:
// 如玩家有个Money的组件,该组件相关的proto文件名:money.proto
//  enum CmdMoney {
//    Cmd_CoinRes = 1102; // 格式: Cmd_MessageName
//  }
//
//  // @Player
//  message CoinRes {
//    int32 totalCoin = 1; // 当前总值
//  }
package game

import "github.com/fish-tennis/gserver/pb"

func (this *Player) SendPlayerEntryGameRes(packet *pb.PlayerEntryGameRes) bool {
	return this.Send(Cmd(pb.CmdLogin_Cmd_PlayerEntryGameRes), packet)
}

func (this *Player) SendCoinRes(packet *pb.CoinRes) bool {
	return this.Send(Cmd(pb.CmdMoney_Cmd_CoinRes), packet)
}
