#服务器进程唯一id
ServerId: 102
#监听客户端
Client:
  Addr: 127.0.0.1:10201
#监听网关
Gate:
  Addr: 127.0.0.1:10202
#监听其他服务器
Server:
  Addr: 127.0.0.1:10203
#数据库
Mongo:
  Uri: mongodb://127.0.0.1:27017
  Db: testdb
#缓存
Redis:
  Uri:
    - 127.0.0.1:6379
  UserName:
  Password:
  Cluster: true