#服务器进程唯一id
ServerId: 201
#social服务器,承载公会等跨玩家协程实体
#监听其他服务器
Server:
  Addr: :20103
#数据库
Mongo:
  Uri: mongodb://127.0.0.1:27017
  Db: testdb
#缓存
Redis:
  Uri:
    - 127.0.0.1:6379
  UserName:
  Password:
  Cluster: false
  DB: 0
#接收告警信息的webhook地址
#AlertWebhook:
