// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: bags.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 容器类型
type ContainerType int32

const (
	ContainerType_ContainerType_None       ContainerType = 0
	ContainerType_ContainerType_CountItem  ContainerType = 1 // 可叠加的普通物品
	ContainerType_ContainerType_UniqueItem ContainerType = 2 // 不可叠加的普通物品(如带限时属性的普通物品)
	ContainerType_ContainerType_Equip      ContainerType = 3 // 装备
)

// Enum value maps for ContainerType.
var (
	ContainerType_name = map[int32]string{
		0: "ContainerType_None",
		1: "ContainerType_CountItem",
		2: "ContainerType_UniqueItem",
		3: "ContainerType_Equip",
	}
	ContainerType_value = map[string]int32{
		"ContainerType_None":       0,
		"ContainerType_CountItem":  1,
		"ContainerType_UniqueItem": 2,
		"ContainerType_Equip":      3,
	}
)

func (x ContainerType) Enum() *ContainerType {
	p := new(ContainerType)
	*p = x
	return p
}

func (x ContainerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerType) Descriptor() protoreflect.EnumDescriptor {
	return file_bags_proto_enumTypes[0].Descriptor()
}

func (ContainerType) Type() protoreflect.EnumType {
	return &file_bags_proto_enumTypes[0]
}

func (x ContainerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerType.Descriptor instead.
func (ContainerType) EnumDescriptor() ([]byte, []int) {
	return file_bags_proto_rawDescGZIP(), []int{0}
}

// 容器内元素数据变化类型
type ElemOpType int32

const (
	ElemOpType_ElemOpType_None   ElemOpType = 0
	ElemOpType_ElemOpType_Add    ElemOpType = 1 // 新加
	ElemOpType_ElemOpType_Update ElemOpType = 2 // 更新属性(不可叠加的元素,如装备)
	ElemOpType_ElemOpType_Delete ElemOpType = 3 // 删除
)

// Enum value maps for ElemOpType.
var (
	ElemOpType_name = map[int32]string{
		0: "ElemOpType_None",
		1: "ElemOpType_Add",
		2: "ElemOpType_Update",
		3: "ElemOpType_Delete",
	}
	ElemOpType_value = map[string]int32{
		"ElemOpType_None":   0,
		"ElemOpType_Add":    1,
		"ElemOpType_Update": 2,
		"ElemOpType_Delete": 3,
	}
)

func (x ElemOpType) Enum() *ElemOpType {
	p := new(ElemOpType)
	*p = x
	return p
}

func (x ElemOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElemOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_bags_proto_enumTypes[1].Descriptor()
}

func (ElemOpType) Type() protoreflect.EnumType {
	return &file_bags_proto_enumTypes[1]
}

func (x ElemOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElemOpType.Descriptor instead.
func (ElemOpType) EnumDescriptor() ([]byte, []int) {
	return file_bags_proto_rawDescGZIP(), []int{1}
}

// 容器更新
// 整合不同的容器,不同的操作类型(增加,更新,删除),都统一在一个消息里面
type ElemContainerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElemOps       []*ElemOp              `protobuf:"bytes,1,rep,name=ElemOps,proto3" json:"ElemOps,omitempty"` // 容器数据变化,增加,更新,删除
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElemContainerUpdate) Reset() {
	*x = ElemContainerUpdate{}
	mi := &file_bags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElemContainerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElemContainerUpdate) ProtoMessage() {}

func (x *ElemContainerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElemContainerUpdate.ProtoReflect.Descriptor instead.
func (*ElemContainerUpdate) Descriptor() ([]byte, []int) {
	return file_bags_proto_rawDescGZIP(), []int{0}
}

func (x *ElemContainerUpdate) GetElemOps() []*ElemOp {
	if x != nil {
		return x.ElemOps
	}
	return nil
}

// 容器内元素数据变化
type ElemOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerType ContainerType          `protobuf:"varint,1,opt,name=ContainerType,proto3,enum=gserver.ContainerType" json:"ContainerType,omitempty"`
	OpType        ElemOpType             `protobuf:"varint,2,opt,name=OpType,proto3,enum=gserver.ElemOpType" json:"OpType,omitempty"`
	ElemData      *anypb.Any             `protobuf:"bytes,3,opt,name=elemData,proto3" json:"elemData,omitempty"` // 元素数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElemOp) Reset() {
	*x = ElemOp{}
	mi := &file_bags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElemOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElemOp) ProtoMessage() {}

func (x *ElemOp) ProtoReflect() protoreflect.Message {
	mi := &file_bags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElemOp.ProtoReflect.Descriptor instead.
func (*ElemOp) Descriptor() ([]byte, []int) {
	return file_bags_proto_rawDescGZIP(), []int{1}
}

func (x *ElemOp) GetContainerType() ContainerType {
	if x != nil {
		return x.ContainerType
	}
	return ContainerType_ContainerType_None
}

func (x *ElemOp) GetOpType() ElemOpType {
	if x != nil {
		return x.OpType
	}
	return ElemOpType_ElemOpType_None
}

func (x *ElemOp) GetElemData() *anypb.Any {
	if x != nil {
		return x.ElemData
	}
	return nil
}

// int64封装成message,用于序列化成google.protobuf.Any
type UniqueId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueId) Reset() {
	*x = UniqueId{}
	mi := &file_bags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueId) ProtoMessage() {}

func (x *UniqueId) ProtoReflect() protoreflect.Message {
	mi := &file_bags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueId.ProtoReflect.Descriptor instead.
func (*UniqueId) Descriptor() ([]byte, []int) {
	return file_bags_proto_rawDescGZIP(), []int{2}
}

func (x *UniqueId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 元素数量
type ElemNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 配置id
	Num           int32                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`     // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElemNum) Reset() {
	*x = ElemNum{}
	mi := &file_bags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElemNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElemNum) ProtoMessage() {}

func (x *ElemNum) ProtoReflect() protoreflect.Message {
	mi := &file_bags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElemNum.ProtoReflect.Descriptor instead.
func (*ElemNum) Descriptor() ([]byte, []int) {
	return file_bags_proto_rawDescGZIP(), []int{3}
}

func (x *ElemNum) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ElemNum) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 背包数据同步给客户端
type BagsSync struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	CountItem     map[int32]int32            `protobuf:"bytes,1,rep,name=CountItem,proto3" json:"CountItem,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`  // 可叠加的普通物品
	UniqueItem    map[int64]*UniqueCountItem `protobuf:"bytes,2,rep,name=UniqueItem,proto3" json:"UniqueItem,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 不可叠加的普通物品
	Equip         map[int64]*Equip           `protobuf:"bytes,3,rep,name=Equip,proto3" json:"Equip,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`           // 装备
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagsSync) Reset() {
	*x = BagsSync{}
	mi := &file_bags_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagsSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagsSync) ProtoMessage() {}

func (x *BagsSync) ProtoReflect() protoreflect.Message {
	mi := &file_bags_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagsSync.ProtoReflect.Descriptor instead.
func (*BagsSync) Descriptor() ([]byte, []int) {
	return file_bags_proto_rawDescGZIP(), []int{4}
}

func (x *BagsSync) GetCountItem() map[int32]int32 {
	if x != nil {
		return x.CountItem
	}
	return nil
}

func (x *BagsSync) GetUniqueItem() map[int64]*UniqueCountItem {
	if x != nil {
		return x.UniqueItem
	}
	return nil
}

func (x *BagsSync) GetEquip() map[int64]*Equip {
	if x != nil {
		return x.Equip
	}
	return nil
}

var File_bags_proto protoreflect.FileDescriptor

const file_bags_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bags.proto\x12\agserver\x1a\x19google/protobuf/any.proto\x1a\tcfg.proto\x1a\n" +
	"item.proto\"@\n" +
	"\x13ElemContainerUpdate\x12)\n" +
	"\aElemOps\x18\x01 \x03(\v2\x0f.gserver.ElemOpR\aElemOps\"\xa5\x01\n" +
	"\x06ElemOp\x12<\n" +
	"\rContainerType\x18\x01 \x01(\x0e2\x16.gserver.ContainerTypeR\rContainerType\x12+\n" +
	"\x06OpType\x18\x02 \x01(\x0e2\x13.gserver.ElemOpTypeR\x06OpType\x120\n" +
	"\belemData\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\belemData\"\x1a\n" +
	"\bUniqueId\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"1\n" +
	"\aElemNum\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x05R\x03Num\"\xa2\x03\n" +
	"\bBagsSync\x12>\n" +
	"\tCountItem\x18\x01 \x03(\v2 .gserver.BagsSync.CountItemEntryR\tCountItem\x12A\n" +
	"\n" +
	"UniqueItem\x18\x02 \x03(\v2!.gserver.BagsSync.UniqueItemEntryR\n" +
	"UniqueItem\x122\n" +
	"\x05Equip\x18\x03 \x03(\v2\x1c.gserver.BagsSync.EquipEntryR\x05Equip\x1a<\n" +
	"\x0eCountItemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aW\n" +
	"\x0fUniqueItemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.gserver.UniqueCountItemR\x05value:\x028\x01\x1aH\n" +
	"\n" +
	"EquipEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.gserver.EquipR\x05value:\x028\x01*{\n" +
	"\rContainerType\x12\x16\n" +
	"\x12ContainerType_None\x10\x00\x12\x1b\n" +
	"\x17ContainerType_CountItem\x10\x01\x12\x1c\n" +
	"\x18ContainerType_UniqueItem\x10\x02\x12\x17\n" +
	"\x13ContainerType_Equip\x10\x03*c\n" +
	"\n" +
	"ElemOpType\x12\x13\n" +
	"\x0fElemOpType_None\x10\x00\x12\x12\n" +
	"\x0eElemOpType_Add\x10\x01\x12\x15\n" +
	"\x11ElemOpType_Update\x10\x02\x12\x15\n" +
	"\x11ElemOpType_Delete\x10\x03B\x06Z\x04./pbb\x06proto3"

var (
	file_bags_proto_rawDescOnce sync.Once
	file_bags_proto_rawDescData []byte
)

func file_bags_proto_rawDescGZIP() []byte {
	file_bags_proto_rawDescOnce.Do(func() {
		file_bags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bags_proto_rawDesc), len(file_bags_proto_rawDesc)))
	})
	return file_bags_proto_rawDescData
}

var file_bags_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bags_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bags_proto_goTypes = []any{
	(ContainerType)(0),          // 0: gserver.ContainerType
	(ElemOpType)(0),             // 1: gserver.ElemOpType
	(*ElemContainerUpdate)(nil), // 2: gserver.ElemContainerUpdate
	(*ElemOp)(nil),              // 3: gserver.ElemOp
	(*UniqueId)(nil),            // 4: gserver.UniqueId
	(*ElemNum)(nil),             // 5: gserver.ElemNum
	(*BagsSync)(nil),            // 6: gserver.BagsSync
	nil,                         // 7: gserver.BagsSync.CountItemEntry
	nil,                         // 8: gserver.BagsSync.UniqueItemEntry
	nil,                         // 9: gserver.BagsSync.EquipEntry
	(*anypb.Any)(nil),           // 10: google.protobuf.Any
	(*UniqueCountItem)(nil),     // 11: gserver.UniqueCountItem
	(*Equip)(nil),               // 12: gserver.Equip
}
var file_bags_proto_depIdxs = []int32{
	3,  // 0: gserver.ElemContainerUpdate.ElemOps:type_name -> gserver.ElemOp
	0,  // 1: gserver.ElemOp.ContainerType:type_name -> gserver.ContainerType
	1,  // 2: gserver.ElemOp.OpType:type_name -> gserver.ElemOpType
	10, // 3: gserver.ElemOp.elemData:type_name -> google.protobuf.Any
	7,  // 4: gserver.BagsSync.CountItem:type_name -> gserver.BagsSync.CountItemEntry
	8,  // 5: gserver.BagsSync.UniqueItem:type_name -> gserver.BagsSync.UniqueItemEntry
	9,  // 6: gserver.BagsSync.Equip:type_name -> gserver.BagsSync.EquipEntry
	11, // 7: gserver.BagsSync.UniqueItemEntry.value:type_name -> gserver.UniqueCountItem
	12, // 8: gserver.BagsSync.EquipEntry.value:type_name -> gserver.Equip
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_bags_proto_init() }
func file_bags_proto_init() {
	if File_bags_proto != nil {
		return
	}
	file_cfg_proto_init()
	file_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bags_proto_rawDesc), len(file_bags_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bags_proto_goTypes,
		DependencyIndexes: file_bags_proto_depIdxs,
		EnumInfos:         file_bags_proto_enumTypes,
		MessageInfos:      file_bags_proto_msgTypes,
	}.Build()
	File_bags_proto = out.File
	file_bags_proto_goTypes = nil
	file_bags_proto_depIdxs = nil
}
