// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.1
// source: baseinfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息号定义
type CmdBaseInfo int32

const (
	CmdBaseInfo_CmdBaseInfo_None      CmdBaseInfo = 0    // 解决"The first enum value must be zero in proto3."的报错
	CmdBaseInfo_Cmd_PlayerEntryGameOk CmdBaseInfo = 1301 // 玩家进游戏服成功,非客户端消息
)

// Enum value maps for CmdBaseInfo.
var (
	CmdBaseInfo_name = map[int32]string{
		0:    "CmdBaseInfo_None",
		1301: "Cmd_PlayerEntryGameOk",
	}
	CmdBaseInfo_value = map[string]int32{
		"CmdBaseInfo_None":      0,
		"Cmd_PlayerEntryGameOk": 1301,
	}
)

func (x CmdBaseInfo) Enum() *CmdBaseInfo {
	p := new(CmdBaseInfo)
	*p = x
	return p
}

func (x CmdBaseInfo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdBaseInfo) Descriptor() protoreflect.EnumDescriptor {
	return file_baseinfo_proto_enumTypes[0].Descriptor()
}

func (CmdBaseInfo) Type() protoreflect.EnumType {
	return &file_baseinfo_proto_enumTypes[0]
}

func (x CmdBaseInfo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdBaseInfo.Descriptor instead.
func (CmdBaseInfo) EnumDescriptor() ([]byte, []int) {
	return file_baseinfo_proto_rawDescGZIP(), []int{0}
}

// 玩家进游戏服成功,非客户端消息
type PlayerEntryGameOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReconnect bool `protobuf:"varint,1,opt,name=isReconnect,proto3" json:"isReconnect,omitempty"`
}

func (x *PlayerEntryGameOk) Reset() {
	*x = PlayerEntryGameOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baseinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerEntryGameOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEntryGameOk) ProtoMessage() {}

func (x *PlayerEntryGameOk) ProtoReflect() protoreflect.Message {
	mi := &file_baseinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEntryGameOk.ProtoReflect.Descriptor instead.
func (*PlayerEntryGameOk) Descriptor() ([]byte, []int) {
	return file_baseinfo_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerEntryGameOk) GetIsReconnect() bool {
	if x != nil {
		return x.IsReconnect
	}
	return false
}

var File_baseinfo_proto protoreflect.FileDescriptor

var file_baseinfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x6b, 0x12, 0x20, 0x0a, 0x0b,
	0x69, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x69, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2a, 0x3f,
	0x0a, 0x0b, 0x43, 0x6d, 0x64, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a,
	0x10, 0x43, 0x6d, 0x64, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x15, 0x43, 0x6d, 0x64, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x6b, 0x10, 0x95, 0x0a, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_baseinfo_proto_rawDescOnce sync.Once
	file_baseinfo_proto_rawDescData = file_baseinfo_proto_rawDesc
)

func file_baseinfo_proto_rawDescGZIP() []byte {
	file_baseinfo_proto_rawDescOnce.Do(func() {
		file_baseinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_baseinfo_proto_rawDescData)
	})
	return file_baseinfo_proto_rawDescData
}

var file_baseinfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_baseinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_baseinfo_proto_goTypes = []interface{}{
	(CmdBaseInfo)(0),          // 0: gserver.CmdBaseInfo
	(*PlayerEntryGameOk)(nil), // 1: gserver.PlayerEntryGameOk
}
var file_baseinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_baseinfo_proto_init() }
func file_baseinfo_proto_init() {
	if File_baseinfo_proto != nil {
		return
	}
	file_player_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_baseinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerEntryGameOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_baseinfo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_baseinfo_proto_goTypes,
		DependencyIndexes: file_baseinfo_proto_depIdxs,
		EnumInfos:         file_baseinfo_proto_enumTypes,
		MessageInfos:      file_baseinfo_proto_msgTypes,
	}.Build()
	File_baseinfo_proto = out.File
	file_baseinfo_proto_rawDesc = nil
	file_baseinfo_proto_goTypes = nil
	file_baseinfo_proto_depIdxs = nil
}
