// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: baseinfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家进游戏服成功,非客户端消息
type PlayerEntryGameOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReconnect   bool                   `protobuf:"varint,1,opt,name=isReconnect,proto3" json:"isReconnect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEntryGameOk) Reset() {
	*x = PlayerEntryGameOk{}
	mi := &file_baseinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEntryGameOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEntryGameOk) ProtoMessage() {}

func (x *PlayerEntryGameOk) ProtoReflect() protoreflect.Message {
	mi := &file_baseinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEntryGameOk.ProtoReflect.Descriptor instead.
func (*PlayerEntryGameOk) Descriptor() ([]byte, []int) {
	return file_baseinfo_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerEntryGameOk) GetIsReconnect() bool {
	if x != nil {
		return x.IsReconnect
	}
	return false
}

type BaseInfoSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *BaseInfo              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfoSync) Reset() {
	*x = BaseInfoSync{}
	mi := &file_baseinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfoSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoSync) ProtoMessage() {}

func (x *BaseInfoSync) ProtoReflect() protoreflect.Message {
	mi := &file_baseinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoSync.ProtoReflect.Descriptor instead.
func (*BaseInfoSync) Descriptor() ([]byte, []int) {
	return file_baseinfo_proto_rawDescGZIP(), []int{1}
}

func (x *BaseInfoSync) GetData() *BaseInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_baseinfo_proto protoreflect.FileDescriptor

const file_baseinfo_proto_rawDesc = "" +
	"\n" +
	"\x0ebaseinfo.proto\x12\agserver\x1a\fplayer.proto\"5\n" +
	"\x11PlayerEntryGameOk\x12 \n" +
	"\visReconnect\x18\x01 \x01(\bR\visReconnect\"5\n" +
	"\fBaseInfoSync\x12%\n" +
	"\x04data\x18\x01 \x01(\v2\x11.gserver.BaseInfoR\x04dataB\x06Z\x04./pbb\x06proto3"

var (
	file_baseinfo_proto_rawDescOnce sync.Once
	file_baseinfo_proto_rawDescData []byte
)

func file_baseinfo_proto_rawDescGZIP() []byte {
	file_baseinfo_proto_rawDescOnce.Do(func() {
		file_baseinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baseinfo_proto_rawDesc), len(file_baseinfo_proto_rawDesc)))
	})
	return file_baseinfo_proto_rawDescData
}

var file_baseinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_baseinfo_proto_goTypes = []any{
	(*PlayerEntryGameOk)(nil), // 0: gserver.PlayerEntryGameOk
	(*BaseInfoSync)(nil),      // 1: gserver.BaseInfoSync
	(*BaseInfo)(nil),          // 2: gserver.BaseInfo
}
var file_baseinfo_proto_depIdxs = []int32{
	2, // 0: gserver.BaseInfoSync.data:type_name -> gserver.BaseInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_baseinfo_proto_init() }
func file_baseinfo_proto_init() {
	if File_baseinfo_proto != nil {
		return
	}
	file_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baseinfo_proto_rawDesc), len(file_baseinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_baseinfo_proto_goTypes,
		DependencyIndexes: file_baseinfo_proto_depIdxs,
		MessageInfos:      file_baseinfo_proto_msgTypes,
	}.Build()
	File_baseinfo_proto = out.File
	file_baseinfo_proto_goTypes = nil
	file_baseinfo_proto_depIdxs = nil
}
