// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.1
// source: cfg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_Color_None   Color = 0
	Color_Color_Red    Color = 1
	Color_Color_Green  Color = 2
	Color_Color_Blue   Color = 3
	Color_Color_Yellow Color = 4
	Color_Color_Gray   Color = 5
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "Color_None",
		1: "Color_Red",
		2: "Color_Green",
		3: "Color_Blue",
		4: "Color_Yellow",
		5: "Color_Gray",
	}
	Color_value = map[string]int32{
		"Color_None":   0,
		"Color_Red":    1,
		"Color_Green":  2,
		"Color_Blue":   3,
		"Color_Yellow": 4,
		"Color_Gray":   5,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{0}
}

// 刷新方式
type RefreshType int32

const (
	RefreshType_RefreshType_None RefreshType = 0 // 解决"The first enum value must be zero in proto3."的报错
	RefreshType_RefreshType_Day  RefreshType = 1 // 每日重置
)

// Enum value maps for RefreshType.
var (
	RefreshType_name = map[int32]string{
		0: "RefreshType_None",
		1: "RefreshType_Day",
	}
	RefreshType_value = map[string]int32{
		"RefreshType_None": 0,
		"RefreshType_Day":  1,
	}
)

func (x RefreshType) Enum() *RefreshType {
	p := new(RefreshType)
	*p = x
	return p
}

func (x RefreshType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefreshType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[1].Descriptor()
}

func (RefreshType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[1]
}

func (x RefreshType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefreshType.Descriptor instead.
func (RefreshType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{1}
}

// 时间类型
type TimeType int32

const (
	TimeType_TimeType_None      TimeType = 0
	TimeType_TimeType_Timestamp TimeType = 1 // 时间戳
	TimeType_TimeType_Date      TimeType = 2 // 日期(格式:20240219)
)

// Enum value maps for TimeType.
var (
	TimeType_name = map[int32]string{
		0: "TimeType_None",
		1: "TimeType_Timestamp",
		2: "TimeType_Date",
	}
	TimeType_value = map[string]int32{
		"TimeType_None":      0,
		"TimeType_Timestamp": 1,
		"TimeType_Date":      2,
	}
)

func (x TimeType) Enum() *TimeType {
	p := new(TimeType)
	*p = x
	return p
}

func (x TimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[2].Descriptor()
}

func (TimeType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[2]
}

func (x TimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeType.Descriptor instead.
func (TimeType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{2}
}

// 物品类型
type ItemType int32

const (
	ItemType_ItemType_None  ItemType = 0 // 普通物品
	ItemType_ItemType_Equip ItemType = 1 // 装备
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ItemType_None",
		1: "ItemType_Equip",
	}
	ItemType_value = map[string]int32{
		"ItemType_None":  0,
		"ItemType_Equip": 1,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[3].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[3]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{3}
}

// 时间类型
type QuestType int32

const (
	QuestType_QuestType_None     QuestType = 0
	QuestType_QuestType_SubQuest QuestType = 1 // 其他系统的子任务(如活动的子任务)
)

// Enum value maps for QuestType.
var (
	QuestType_name = map[int32]string{
		0: "QuestType_None",
		1: "QuestType_SubQuest",
	}
	QuestType_value = map[string]int32{
		"QuestType_None":     0,
		"QuestType_SubQuest": 1,
	}
)

func (x QuestType) Enum() *QuestType {
	p := new(QuestType)
	*p = x
	return p
}

func (x QuestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[4].Descriptor()
}

func (QuestType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[4]
}

func (x QuestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestType.Descriptor instead.
func (QuestType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{4}
}

// 物品数量
type ItemNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId int32 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 物品配置id
	Num   int32 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`     // 物品数量
}

func (x *ItemNum) Reset() {
	*x = ItemNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemNum) ProtoMessage() {}

func (x *ItemNum) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemNum.ProtoReflect.Descriptor instead.
func (*ItemNum) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{0}
}

func (x *ItemNum) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ItemNum) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 物品配置
type ItemCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId    int32  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Detail   string `protobuf:"bytes,3,opt,name=Detail,proto3" json:"Detail,omitempty"`
	ItemType int32  `protobuf:"varint,4,opt,name=ItemType,proto3" json:"ItemType,omitempty"` // 物品类型(enum ItemType)
	TimeType int32  `protobuf:"varint,5,opt,name=TimeType,proto3" json:"TimeType,omitempty"` // 时间类型(enum TimeType)
	Timeout  int32  `protobuf:"varint,6,opt,name=Timeout,proto3" json:"Timeout,omitempty"`   // 结束时间
}

func (x *ItemCfg) Reset() {
	*x = ItemCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCfg) ProtoMessage() {}

func (x *ItemCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCfg.ProtoReflect.Descriptor instead.
func (*ItemCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{1}
}

func (x *ItemCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ItemCfg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemCfg) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ItemCfg) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *ItemCfg) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *ItemCfg) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// 添加物品参数
type AddItemArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId    int32 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`       // 物品配置id
	Num      int32 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`           // 物品数量
	TimeType int32 `protobuf:"varint,3,opt,name=TimeType,proto3" json:"TimeType,omitempty"` // 时间类型(enum TimeType)
	Timeout  int32 `protobuf:"varint,4,opt,name=Timeout,proto3" json:"Timeout,omitempty"`   // 结束时间
	Source   int32 `protobuf:"varint,5,opt,name=Source,proto3" json:"Source,omitempty"`     // 来源(一般用于数据分析)
}

func (x *AddItemArg) Reset() {
	*x = AddItemArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemArg) ProtoMessage() {}

func (x *AddItemArg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemArg.ProtoReflect.Descriptor instead.
func (*AddItemArg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemArg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *AddItemArg) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *AddItemArg) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *AddItemArg) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *AddItemArg) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

// 删除物品参数
type DelItemArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId int64 `protobuf:"varint,1,opt,name=UniqueId,proto3" json:"UniqueId,omitempty"` // 唯一id(删除指定的不可叠加的物品才需要)
	CfgId    int32 `protobuf:"varint,2,opt,name=CfgId,proto3" json:"CfgId,omitempty"`       // 物品配置id
	Num      int32 `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`           // 物品数量
	Source   int32 `protobuf:"varint,4,opt,name=Source,proto3" json:"Source,omitempty"`     // 来源(一般用于数据分析)
}

func (x *DelItemArg) Reset() {
	*x = DelItemArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelItemArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelItemArg) ProtoMessage() {}

func (x *DelItemArg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelItemArg.ProtoReflect.Descriptor instead.
func (*DelItemArg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{3}
}

func (x *DelItemArg) GetUniqueId() int64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

func (x *DelItemArg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *DelItemArg) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *DelItemArg) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

// 任务基础配置
type BaseQuestCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId     int32         `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Name      string        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	QuestType int32         `protobuf:"varint,3,opt,name=QuestType,proto3" json:"QuestType,omitempty"` // 任务类型(enum QuestType)
	Rewards   []*AddItemArg `protobuf:"bytes,4,rep,name=Rewards,proto3" json:"Rewards,omitempty"`      // 任务奖励
	PreQuest  int32         `protobuf:"varint,5,opt,name=PreQuest,proto3" json:"PreQuest,omitempty"`   // 前置任务
	Detail    string        `protobuf:"bytes,6,opt,name=Detail,proto3" json:"Detail,omitempty"`        // 任务描述
}

func (x *BaseQuestCfg) Reset() {
	*x = BaseQuestCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseQuestCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseQuestCfg) ProtoMessage() {}

func (x *BaseQuestCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseQuestCfg.ProtoReflect.Descriptor instead.
func (*BaseQuestCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{4}
}

func (x *BaseQuestCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *BaseQuestCfg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseQuestCfg) GetQuestType() int32 {
	if x != nil {
		return x.QuestType
	}
	return 0
}

func (x *BaseQuestCfg) GetRewards() []*AddItemArg {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *BaseQuestCfg) GetPreQuest() int32 {
	if x != nil {
		return x.PreQuest
	}
	return 0
}

func (x *BaseQuestCfg) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// 条件基础配置
type BaseConditionCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"` // 条件类型(enum ConditionType)
	Key  string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`    // 关键字,如ConditionType_PlayerPropertyCompare对应的属性名
	Op   string `protobuf:"bytes,3,opt,name=Op,proto3" json:"Op,omitempty"`      // 操作符 = > >= < <=
	Arg  int32  `protobuf:"varint,4,opt,name=Arg,proto3" json:"Arg,omitempty"`   // 参数
}

func (x *BaseConditionCfg) Reset() {
	*x = BaseConditionCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseConditionCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseConditionCfg) ProtoMessage() {}

func (x *BaseConditionCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseConditionCfg.ProtoReflect.Descriptor instead.
func (*BaseConditionCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{5}
}

func (x *BaseConditionCfg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BaseConditionCfg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BaseConditionCfg) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *BaseConditionCfg) GetArg() int32 {
	if x != nil {
		return x.Arg
	}
	return 0
}

// 进度基础配置
type BaseProgressCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      int32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`           // 进度类型(enum ProgressType)
	CountType int32 `protobuf:"varint,2,opt,name=CountType,proto3" json:"CountType,omitempty"` // 计数类型
	Total     int32 `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`         // 总进度要求
}

func (x *BaseProgressCfg) Reset() {
	*x = BaseProgressCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseProgressCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseProgressCfg) ProtoMessage() {}

func (x *BaseProgressCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseProgressCfg.ProtoReflect.Descriptor instead.
func (*BaseProgressCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{6}
}

func (x *BaseProgressCfg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BaseProgressCfg) GetCountType() int32 {
	if x != nil {
		return x.CountType
	}
	return 0
}

func (x *BaseProgressCfg) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 活动基础配置
type BaseActivityCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId             int32          `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Name              string         `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Detail            string         `protobuf:"bytes,3,opt,name=Detail,proto3" json:"Detail,omitempty"`
	Template          string         `protobuf:"bytes,4,opt,name=Template,proto3" json:"Template,omitempty"`                     // 活动模板
	RefreshType       int32          `protobuf:"varint,5,opt,name=RefreshType,proto3" json:"RefreshType,omitempty"`              // 刷新机制
	CycleType         int32          `protobuf:"varint,6,opt,name=CycleType,proto3" json:"CycleType,omitempty"`                  // 活动周期
	TimeType          int32          `protobuf:"varint,7,opt,name=TimeType,proto3" json:"TimeType,omitempty"`                    // 时间类型
	BeginTime         int32          `protobuf:"varint,8,opt,name=BeginTime,proto3" json:"BeginTime,omitempty"`                  // 开始时间
	EndTime           int32          `protobuf:"varint,9,opt,name=EndTime,proto3" json:"EndTime,omitempty"`                      // 结束时间
	Exchanges         []*ExchangeCfg `protobuf:"bytes,10,rep,name=Exchanges,proto3" json:"Exchanges,omitempty"`                  // 兑换配置
	IsOff             bool           `protobuf:"varint,11,opt,name=IsOff,proto3" json:"IsOff,omitempty"`                         // 是否关闭
	RemoveDataWhenEnd bool           `protobuf:"varint,12,opt,name=RemoveDataWhenEnd,proto3" json:"RemoveDataWhenEnd,omitempty"` // 活动结束时,是否删除活动数据
	MinPlayerLevel    int32          `protobuf:"varint,14,opt,name=MinPlayerLevel,proto3" json:"MinPlayerLevel,omitempty"`       // 参与活动的最低玩家等级要求
	MaxPlayerLevel    int32          `protobuf:"varint,15,opt,name=MaxPlayerLevel,proto3" json:"MaxPlayerLevel,omitempty"`       // 参与活动的最大玩家等级上限
	Quests            []int32        `protobuf:"varint,16,rep,packed,name=Quests,proto3" json:"Quests,omitempty"`                // 活动子任务
}

func (x *BaseActivityCfg) Reset() {
	*x = BaseActivityCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseActivityCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseActivityCfg) ProtoMessage() {}

func (x *BaseActivityCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseActivityCfg.ProtoReflect.Descriptor instead.
func (*BaseActivityCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{7}
}

func (x *BaseActivityCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *BaseActivityCfg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseActivityCfg) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *BaseActivityCfg) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *BaseActivityCfg) GetRefreshType() int32 {
	if x != nil {
		return x.RefreshType
	}
	return 0
}

func (x *BaseActivityCfg) GetCycleType() int32 {
	if x != nil {
		return x.CycleType
	}
	return 0
}

func (x *BaseActivityCfg) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *BaseActivityCfg) GetBeginTime() int32 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *BaseActivityCfg) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BaseActivityCfg) GetExchanges() []*ExchangeCfg {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *BaseActivityCfg) GetIsOff() bool {
	if x != nil {
		return x.IsOff
	}
	return false
}

func (x *BaseActivityCfg) GetRemoveDataWhenEnd() bool {
	if x != nil {
		return x.RemoveDataWhenEnd
	}
	return false
}

func (x *BaseActivityCfg) GetMinPlayerLevel() int32 {
	if x != nil {
		return x.MinPlayerLevel
	}
	return 0
}

func (x *BaseActivityCfg) GetMaxPlayerLevel() int32 {
	if x != nil {
		return x.MaxPlayerLevel
	}
	return 0
}

func (x *BaseActivityCfg) GetQuests() []int32 {
	if x != nil {
		return x.Quests
	}
	return nil
}

// 兑换配置
type ExchangeCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId        int32         `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	ConsumeItems []*DelItemArg `protobuf:"bytes,2,rep,name=ConsumeItems,proto3" json:"ConsumeItems,omitempty"` // 需要消耗的物品
	Rewards      []*AddItemArg `protobuf:"bytes,3,rep,name=Rewards,proto3" json:"Rewards,omitempty"`           // 获得物品
	CountLimit   int32         `protobuf:"varint,4,opt,name=CountLimit,proto3" json:"CountLimit,omitempty"`    // 兑换次数限制
}

func (x *ExchangeCfg) Reset() {
	*x = ExchangeCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCfg) ProtoMessage() {}

func (x *ExchangeCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCfg.ProtoReflect.Descriptor instead.
func (*ExchangeCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{8}
}

func (x *ExchangeCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ExchangeCfg) GetConsumeItems() []*DelItemArg {
	if x != nil {
		return x.ConsumeItems
	}
	return nil
}

func (x *ExchangeCfg) GetRewards() []*AddItemArg {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *ExchangeCfg) GetCountLimit() int32 {
	if x != nil {
		return x.CountLimit
	}
	return 0
}

// 升级经验
type LevelExp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level   int32 `protobuf:"varint,1,opt,name=Level,proto3" json:"Level,omitempty"`     // 等级
	NeedExp int32 `protobuf:"varint,2,opt,name=NeedExp,proto3" json:"NeedExp,omitempty"` // 升到该等级需要的经验值
}

func (x *LevelExp) Reset() {
	*x = LevelExp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LevelExp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelExp) ProtoMessage() {}

func (x *LevelExp) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelExp.ProtoReflect.Descriptor instead.
func (*LevelExp) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{9}
}

func (x *LevelExp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LevelExp) GetNeedExp() int32 {
	if x != nil {
		return x.NeedExp
	}
	return 0
}

var File_cfg_proto protoreflect.FileDescriptor

var file_cfg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x66, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22, 0x9d, 0x01, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d,
	0x43, 0x66, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x41, 0x72, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x68, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x72, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x55, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0xb9, 0x01, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x43, 0x66, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x51, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2d, 0x0a, 0x07, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x41, 0x72, 0x67, 0x52, 0x07, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x72, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x50, 0x72, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0x5a, 0x0a, 0x10, 0x42, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x66, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x4f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x41, 0x72, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x72, 0x67, 0x22, 0x59,
	0x0a, 0x0f, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43, 0x66,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xe3, 0x03, 0x0a, 0x0f, 0x42, 0x61,
	0x73, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x66, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66,
	0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54,
	0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54,
	0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x65, 0x67, 0x69, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x32, 0x0a, 0x09, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x66, 0x67, 0x52, 0x09, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x4f, 0x66, 0x66, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x4f, 0x66, 0x66, 0x12, 0x2c, 0x0a, 0x11, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x57, 0x68, 0x65, 0x6e, 0x45, 0x6e, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x57, 0x68, 0x65, 0x6e, 0x45, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x69, 0x6e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x4d, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x26, 0x0a, 0x0e, 0x4d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x4d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x51, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22,
	0xab, 0x01, 0x0a, 0x0b, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x66, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x72, 0x67,
	0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2d,
	0x0a, 0x07, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x41, 0x72, 0x67, 0x52, 0x07, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3a, 0x0a,
	0x08, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x45, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x4e, 0x65, 0x65, 0x64, 0x45, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x4e, 0x65, 0x65, 0x64, 0x45, 0x78, 0x70, 0x2a, 0x69, 0x0a, 0x05, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x52, 0x65, 0x64, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x47, 0x72, 0x65, 0x65, 0x6e,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x42, 0x6c, 0x75, 0x65,
	0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x59, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x47, 0x72,
	0x61, 0x79, 0x10, 0x05, 0x2a, 0x38, 0x0a, 0x0b, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x61, 0x79, 0x10, 0x01, 0x2a, 0x48,
	0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x69,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a,
	0x12, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x44, 0x61, 0x74, 0x65, 0x10, 0x02, 0x2a, 0x31, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x10, 0x01, 0x2a, 0x37, 0x0a, 0x09, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x53, 0x75, 0x62, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cfg_proto_rawDescOnce sync.Once
	file_cfg_proto_rawDescData = file_cfg_proto_rawDesc
)

func file_cfg_proto_rawDescGZIP() []byte {
	file_cfg_proto_rawDescOnce.Do(func() {
		file_cfg_proto_rawDescData = protoimpl.X.CompressGZIP(file_cfg_proto_rawDescData)
	})
	return file_cfg_proto_rawDescData
}

var file_cfg_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_cfg_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cfg_proto_goTypes = []interface{}{
	(Color)(0),               // 0: gserver.Color
	(RefreshType)(0),         // 1: gserver.RefreshType
	(TimeType)(0),            // 2: gserver.TimeType
	(ItemType)(0),            // 3: gserver.ItemType
	(QuestType)(0),           // 4: gserver.QuestType
	(*ItemNum)(nil),          // 5: gserver.ItemNum
	(*ItemCfg)(nil),          // 6: gserver.ItemCfg
	(*AddItemArg)(nil),       // 7: gserver.AddItemArg
	(*DelItemArg)(nil),       // 8: gserver.DelItemArg
	(*BaseQuestCfg)(nil),     // 9: gserver.BaseQuestCfg
	(*BaseConditionCfg)(nil), // 10: gserver.BaseConditionCfg
	(*BaseProgressCfg)(nil),  // 11: gserver.BaseProgressCfg
	(*BaseActivityCfg)(nil),  // 12: gserver.BaseActivityCfg
	(*ExchangeCfg)(nil),      // 13: gserver.ExchangeCfg
	(*LevelExp)(nil),         // 14: gserver.LevelExp
}
var file_cfg_proto_depIdxs = []int32{
	7,  // 0: gserver.BaseQuestCfg.Rewards:type_name -> gserver.AddItemArg
	13, // 1: gserver.BaseActivityCfg.Exchanges:type_name -> gserver.ExchangeCfg
	8,  // 2: gserver.ExchangeCfg.ConsumeItems:type_name -> gserver.DelItemArg
	7,  // 3: gserver.ExchangeCfg.Rewards:type_name -> gserver.AddItemArg
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_cfg_proto_init() }
func file_cfg_proto_init() {
	if File_cfg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cfg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelItemArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseQuestCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseConditionCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseProgressCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseActivityCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LevelExp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cfg_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cfg_proto_goTypes,
		DependencyIndexes: file_cfg_proto_depIdxs,
		EnumInfos:         file_cfg_proto_enumTypes,
		MessageInfos:      file_cfg_proto_msgTypes,
	}.Build()
	File_cfg_proto = out.File
	file_cfg_proto_rawDesc = nil
	file_cfg_proto_goTypes = nil
	file_cfg_proto_depIdxs = nil
}
