// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: cfg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_Color_None   Color = 0
	Color_Color_Red    Color = 1
	Color_Color_Green  Color = 2
	Color_Color_Blue   Color = 3
	Color_Color_Yellow Color = 4
	Color_Color_Gray   Color = 5
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "Color_None",
		1: "Color_Red",
		2: "Color_Green",
		3: "Color_Blue",
		4: "Color_Yellow",
		5: "Color_Gray",
	}
	Color_value = map[string]int32{
		"Color_None":   0,
		"Color_Red":    1,
		"Color_Green":  2,
		"Color_Blue":   3,
		"Color_Yellow": 4,
		"Color_Gray":   5,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{0}
}

// 刷新方式
type RefreshType int32

const (
	RefreshType_RefreshType_None RefreshType = 0 // 解决"The first enum value must be zero in proto3."的报错
	RefreshType_RefreshType_Day  RefreshType = 1 // 每日重置
)

// Enum value maps for RefreshType.
var (
	RefreshType_name = map[int32]string{
		0: "RefreshType_None",
		1: "RefreshType_Day",
	}
	RefreshType_value = map[string]int32{
		"RefreshType_None": 0,
		"RefreshType_Day":  1,
	}
)

func (x RefreshType) Enum() *RefreshType {
	p := new(RefreshType)
	*p = x
	return p
}

func (x RefreshType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefreshType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[1].Descriptor()
}

func (RefreshType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[1]
}

func (x RefreshType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefreshType.Descriptor instead.
func (RefreshType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{1}
}

// 时间类型
type TimeType int32

const (
	TimeType_TimeType_None      TimeType = 0
	TimeType_TimeType_Timestamp TimeType = 1 // 时间戳
	TimeType_TimeType_Date      TimeType = 2 // 日期(格式:20240219)
)

// Enum value maps for TimeType.
var (
	TimeType_name = map[int32]string{
		0: "TimeType_None",
		1: "TimeType_Timestamp",
		2: "TimeType_Date",
	}
	TimeType_value = map[string]int32{
		"TimeType_None":      0,
		"TimeType_Timestamp": 1,
		"TimeType_Date":      2,
	}
)

func (x TimeType) Enum() *TimeType {
	p := new(TimeType)
	*p = x
	return p
}

func (x TimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[2].Descriptor()
}

func (TimeType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[2]
}

func (x TimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeType.Descriptor instead.
func (TimeType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{2}
}

// 物品类型
type ItemType int32

const (
	ItemType_ItemType_None  ItemType = 0 // 普通物品
	ItemType_ItemType_Equip ItemType = 1 // 装备
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ItemType_None",
		1: "ItemType_Equip",
	}
	ItemType_value = map[string]int32{
		"ItemType_None":  0,
		"ItemType_Equip": 1,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[3].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[3]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{3}
}

// 物品子类
type ItemSubType int32

const (
	ItemSubType_ItemSubType_None  ItemSubType = 0
	ItemSubType_ItemSubType_Gold  ItemSubType = 1 // 金币
	ItemSubType_ItemSubType_Exp   ItemSubType = 2 // 经验丹
	ItemSubType_ItemSubType_Quest ItemSubType = 3 // 任务物品
)

// Enum value maps for ItemSubType.
var (
	ItemSubType_name = map[int32]string{
		0: "ItemSubType_None",
		1: "ItemSubType_Gold",
		2: "ItemSubType_Exp",
		3: "ItemSubType_Quest",
	}
	ItemSubType_value = map[string]int32{
		"ItemSubType_None":  0,
		"ItemSubType_Gold":  1,
		"ItemSubType_Exp":   2,
		"ItemSubType_Quest": 3,
	}
)

func (x ItemSubType) Enum() *ItemSubType {
	p := new(ItemSubType)
	*p = x
	return p
}

func (x ItemSubType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemSubType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[4].Descriptor()
}

func (ItemSubType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[4]
}

func (x ItemSubType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemSubType.Descriptor instead.
func (ItemSubType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{4}
}

// 物品分类
type ItemCategory int32

const (
	ItemCategory_ItemCategory_None ItemCategory = 0
)

// Enum value maps for ItemCategory.
var (
	ItemCategory_name = map[int32]string{
		0: "ItemCategory_None",
	}
	ItemCategory_value = map[string]int32{
		"ItemCategory_None": 0,
	}
)

func (x ItemCategory) Enum() *ItemCategory {
	p := new(ItemCategory)
	*p = x
	return p
}

func (x ItemCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[5].Descriptor()
}

func (ItemCategory) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[5]
}

func (x ItemCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemCategory.Descriptor instead.
func (ItemCategory) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{5}
}

// 物品显示类型
type ItemViewType int32

const (
	ItemViewType_ItemViewType_None ItemViewType = 0
	ItemViewType_ItemViewType_Hide ItemViewType = 1 // 隐藏,不显示在背包中,不占背包格子
)

// Enum value maps for ItemViewType.
var (
	ItemViewType_name = map[int32]string{
		0: "ItemViewType_None",
		1: "ItemViewType_Hide",
	}
	ItemViewType_value = map[string]int32{
		"ItemViewType_None": 0,
		"ItemViewType_Hide": 1,
	}
)

func (x ItemViewType) Enum() *ItemViewType {
	p := new(ItemViewType)
	*p = x
	return p
}

func (x ItemViewType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemViewType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[6].Descriptor()
}

func (ItemViewType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[6]
}

func (x ItemViewType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemViewType.Descriptor instead.
func (ItemViewType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{6}
}

// 特殊的物品Id
type ItemId int32

const (
	ItemId_ItemId_None ItemId = 0
	ItemId_ItemId_Coin ItemId = 1 // 金币
)

// Enum value maps for ItemId.
var (
	ItemId_name = map[int32]string{
		0: "ItemId_None",
		1: "ItemId_Coin",
	}
	ItemId_value = map[string]int32{
		"ItemId_None": 0,
		"ItemId_Coin": 1,
	}
)

func (x ItemId) Enum() *ItemId {
	p := new(ItemId)
	*p = x
	return p
}

func (x ItemId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemId) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[7].Descriptor()
}

func (ItemId) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[7]
}

func (x ItemId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemId.Descriptor instead.
func (ItemId) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{7}
}

// 任务类型 (NOTE:根据项目实际需求,自行调整)
type QuestType int32

const (
	QuestType_QuestType_None        QuestType = 0
	QuestType_QuestType_SubQuest    QuestType = 1 // 其他系统的子任务(如活动的子任务)
	QuestType_QuestType_Achievement QuestType = 2 // 成就
)

// Enum value maps for QuestType.
var (
	QuestType_name = map[int32]string{
		0: "QuestType_None",
		1: "QuestType_SubQuest",
		2: "QuestType_Achievement",
	}
	QuestType_value = map[string]int32{
		"QuestType_None":        0,
		"QuestType_SubQuest":    1,
		"QuestType_Achievement": 2,
	}
)

func (x QuestType) Enum() *QuestType {
	p := new(QuestType)
	*p = x
	return p
}

func (x QuestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestType) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[8].Descriptor()
}

func (QuestType) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[8]
}

func (x QuestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestType.Descriptor instead.
func (QuestType) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{8}
}

// 任务分类 (NOTE:根据项目实际需求,自行调整)
type QuestCategory int32

const (
	QuestCategory_QuestCategory_None QuestCategory = 0
)

// Enum value maps for QuestCategory.
var (
	QuestCategory_name = map[int32]string{
		0: "QuestCategory_None",
	}
	QuestCategory_value = map[string]int32{
		"QuestCategory_None": 0,
	}
)

func (x QuestCategory) Enum() *QuestCategory {
	p := new(QuestCategory)
	*p = x
	return p
}

func (x QuestCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[9].Descriptor()
}

func (QuestCategory) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[9]
}

func (x QuestCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestCategory.Descriptor instead.
func (QuestCategory) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{9}
}

// 兑换分类
type ExchangeCategory int32

const (
	ExchangeCategory_ExchangeCategory_None ExchangeCategory = 0
	ExchangeCategory_ExchangeCategory_Shop ExchangeCategory = 1 // 商店
)

// Enum value maps for ExchangeCategory.
var (
	ExchangeCategory_name = map[int32]string{
		0: "ExchangeCategory_None",
		1: "ExchangeCategory_Shop",
	}
	ExchangeCategory_value = map[string]int32{
		"ExchangeCategory_None": 0,
		"ExchangeCategory_Shop": 1,
	}
)

func (x ExchangeCategory) Enum() *ExchangeCategory {
	p := new(ExchangeCategory)
	*p = x
	return p
}

func (x ExchangeCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExchangeCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_proto_enumTypes[10].Descriptor()
}

func (ExchangeCategory) Type() protoreflect.EnumType {
	return &file_cfg_proto_enumTypes[10]
}

func (x ExchangeCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExchangeCategory.Descriptor instead.
func (ExchangeCategory) EnumDescriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{10}
}

// 物品数量
type ItemNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 物品配置id
	Num           int32                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`     // 物品数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemNum) Reset() {
	*x = ItemNum{}
	mi := &file_cfg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemNum) ProtoMessage() {}

func (x *ItemNum) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemNum.ProtoReflect.Descriptor instead.
func (*ItemNum) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{0}
}

func (x *ItemNum) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ItemNum) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// Id和数量
type IdCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"` // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdCount) Reset() {
	*x = IdCount{}
	mi := &file_cfg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdCount) ProtoMessage() {}

func (x *IdCount) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdCount.ProtoReflect.Descriptor instead.
func (*IdCount) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{1}
}

func (x *IdCount) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IdCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 物品配置
type ItemCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=Detail,proto3" json:"Detail,omitempty"`
	ItemType      int32                  `protobuf:"varint,4,opt,name=ItemType,proto3" json:"ItemType,omitempty"`                                                                               // 物品类型(enum ItemType)
	SubType       int32                  `protobuf:"varint,5,opt,name=SubType,proto3" json:"SubType,omitempty"`                                                                                 // 物品子类(enum ItemSubType)
	Category      int32                  `protobuf:"varint,6,opt,name=Category,proto3" json:"Category,omitempty"`                                                                               // 物品分类(enum ItemCategory)
	Args          []int32                `protobuf:"varint,7,rep,packed,name=Args,proto3" json:"Args,omitempty"`                                                                                // 参数列表(比如ItemSubType=ItemSubType_Exp是,表示加经验的数值)
	TimeType      int32                  `protobuf:"varint,8,opt,name=TimeType,proto3" json:"TimeType,omitempty"`                                                                               // 限时道具的时间类型(enum TimeType)
	Timeout       int32                  `protobuf:"varint,9,opt,name=Timeout,proto3" json:"Timeout,omitempty"`                                                                                 // 限时道具的时限
	ViewType      int32                  `protobuf:"varint,10,opt,name=ViewType,proto3" json:"ViewType,omitempty"`                                                                              // 物品显示类型(enum ItemViewType)
	Properties    map[string]string      `protobuf:"bytes,11,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	Icon          string                 `protobuf:"bytes,12,opt,name=Icon,proto3" json:"Icon,omitempty"`                                                                                       // 物品图标(客户端使用)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCfg) Reset() {
	*x = ItemCfg{}
	mi := &file_cfg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCfg) ProtoMessage() {}

func (x *ItemCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCfg.ProtoReflect.Descriptor instead.
func (*ItemCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{2}
}

func (x *ItemCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ItemCfg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemCfg) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ItemCfg) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *ItemCfg) GetSubType() int32 {
	if x != nil {
		return x.SubType
	}
	return 0
}

func (x *ItemCfg) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *ItemCfg) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ItemCfg) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *ItemCfg) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ItemCfg) GetViewType() int32 {
	if x != nil {
		return x.ViewType
	}
	return 0
}

func (x *ItemCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ItemCfg) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

// 添加元素参数
type AddElemArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`                                                                                    // 配置id
	Num           int32                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`                                                                                        // 数量
	TimeType      int32                  `protobuf:"varint,3,opt,name=TimeType,proto3" json:"TimeType,omitempty"`                                                                              // 时间类型(enum TimeType)
	Timeout       int32                  `protobuf:"varint,4,opt,name=Timeout,proto3" json:"Timeout,omitempty"`                                                                                // 结束时间(TimeType=Timestamp时,表示超时秒数 TimeType=Date时,表示日期,如20240219)
	Source        int32                  `protobuf:"varint,5,opt,name=Source,proto3" json:"Source,omitempty"`                                                                                  // 来源(一般用于数据分析)
	Properties    map[string]string      `protobuf:"bytes,6,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddElemArg) Reset() {
	*x = AddElemArg{}
	mi := &file_cfg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddElemArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddElemArg) ProtoMessage() {}

func (x *AddElemArg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddElemArg.ProtoReflect.Descriptor instead.
func (*AddElemArg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{3}
}

func (x *AddElemArg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *AddElemArg) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *AddElemArg) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *AddElemArg) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *AddElemArg) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *AddElemArg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// 删除元素参数
type DelElemArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqueId      int64                  `protobuf:"varint,1,opt,name=UniqueId,proto3" json:"UniqueId,omitempty"`                                                                              // 唯一id(删除指定的不可叠加的元素才需要)
	CfgId         int32                  `protobuf:"varint,2,opt,name=CfgId,proto3" json:"CfgId,omitempty"`                                                                                    // 配置id
	Num           int32                  `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`                                                                                        // 数量
	Source        int32                  `protobuf:"varint,4,opt,name=Source,proto3" json:"Source,omitempty"`                                                                                  // 来源(一般用于数据分析)
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelElemArg) Reset() {
	*x = DelElemArg{}
	mi := &file_cfg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelElemArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelElemArg) ProtoMessage() {}

func (x *DelElemArg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelElemArg.ProtoReflect.Descriptor instead.
func (*DelElemArg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{4}
}

func (x *DelElemArg) GetUniqueId() int64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

func (x *DelElemArg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *DelElemArg) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *DelElemArg) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *DelElemArg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// CfgId + Arg
type CfgArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 配置id
	Arg           int32                  `protobuf:"varint,2,opt,name=Arg,proto3" json:"Arg,omitempty"`     // 单个参数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CfgArg) Reset() {
	*x = CfgArg{}
	mi := &file_cfg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CfgArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgArg) ProtoMessage() {}

func (x *CfgArg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgArg.ProtoReflect.Descriptor instead.
func (*CfgArg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{5}
}

func (x *CfgArg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *CfgArg) GetArg() int32 {
	if x != nil {
		return x.Arg
	}
	return 0
}

// CfgId + Args
type CfgArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`      // 配置id
	Args          []int32                `protobuf:"varint,2,rep,packed,name=Args,proto3" json:"Args,omitempty"` // 参数值数组
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CfgArgs) Reset() {
	*x = CfgArgs{}
	mi := &file_cfg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CfgArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgArgs) ProtoMessage() {}

func (x *CfgArgs) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgArgs.ProtoReflect.Descriptor instead.
func (*CfgArgs) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{6}
}

func (x *CfgArgs) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *CfgArgs) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

// CfgId + Args + Options
type CfgArgOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`            // 配置id
	Args          []int32                `protobuf:"varint,2,rep,packed,name=Args,proto3" json:"Args,omitempty"`       // 参数值数组
	Options       []int32                `protobuf:"varint,3,rep,packed,name=Options,proto3" json:"Options,omitempty"` // 可选参数数组
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CfgArgOptions) Reset() {
	*x = CfgArgOptions{}
	mi := &file_cfg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CfgArgOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgArgOptions) ProtoMessage() {}

func (x *CfgArgOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgArgOptions.ProtoReflect.Descriptor instead.
func (*CfgArgOptions) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{7}
}

func (x *CfgArgOptions) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *CfgArgOptions) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CfgArgOptions) GetOptions() []int32 {
	if x != nil {
		return x.Options
	}
	return nil
}

// Type + Value
type TypeValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`   // 类型
	Value         int32                  `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"` // 值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeValue) Reset() {
	*x = TypeValue{}
	mi := &file_cfg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeValue) ProtoMessage() {}

func (x *TypeValue) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeValue.ProtoReflect.Descriptor instead.
func (*TypeValue) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{8}
}

func (x *TypeValue) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TypeValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 任务配置
type QuestCfg struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CfgId              int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	QuestType          int32                  `protobuf:"varint,3,opt,name=QuestType,proto3" json:"QuestType,omitempty"`                                                                             // 任务类型(enum QuestType)
	RefreshType        int32                  `protobuf:"varint,4,opt,name=RefreshType,proto3" json:"RefreshType,omitempty"`                                                                         // 刷新机制(enum RefreshType)
	Category           int32                  `protobuf:"varint,5,opt,name=Category,proto3" json:"Category,omitempty"`                                                                               // 任务分类(enum QuestCategory)
	Rewards            []*AddElemArg          `protobuf:"bytes,6,rep,name=Rewards,proto3" json:"Rewards,omitempty"`                                                                                  // 任务奖励
	PreQuest           int32                  `protobuf:"varint,7,opt,name=PreQuest,proto3" json:"PreQuest,omitempty"`                                                                               // 前置任务
	NextQuests         []int32                `protobuf:"varint,8,rep,packed,name=NextQuests,proto3" json:"NextQuests,omitempty"`                                                                    // 完成该任务后,自动接后续的任务(任务链)
	Conditions         []*ConditionCfg        `protobuf:"bytes,9,rep,name=Conditions,proto3" json:"Conditions,omitempty"`                                                                            // 任务条件
	Progress           *ProgressCfg           `protobuf:"bytes,10,opt,name=Progress,proto3" json:"Progress,omitempty"`                                                                               // 任务进度(收集类物品,此字段可能为空)
	Properties         map[string]string      `protobuf:"bytes,11,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	Detail             string                 `protobuf:"bytes,12,opt,name=Detail,proto3" json:"Detail,omitempty"`                                                                                   // 任务描述
	PlayerLevel        int32                  `protobuf:"varint,13,opt,name=PlayerLevel,proto3" json:"PlayerLevel,omitempty"`                                                                        // 玩家等级限制(0表示不限制)
	Collects           []*ItemNum             `protobuf:"bytes,14,rep,name=Collects,proto3" json:"Collects,omitempty"`                                                                               // 需要收集的物品(一般是任务物品)
	ConditionTemplates []*CfgArgOptions       `protobuf:"bytes,21,rep,name=ConditionTemplates,proto3" json:"ConditionTemplates,omitempty"`                                                           // 关联的配置模板id和参数,简化配置表用,业务代码不要调用
	ProgressTemplate   *CfgArg                `protobuf:"bytes,22,opt,name=ProgressTemplate,proto3" json:"ProgressTemplate,omitempty"`                                                               // 关联的配置模板id和参数,简化配置表用,业务代码不要调用
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuestCfg) Reset() {
	*x = QuestCfg{}
	mi := &file_cfg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestCfg) ProtoMessage() {}

func (x *QuestCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestCfg.ProtoReflect.Descriptor instead.
func (*QuestCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{9}
}

func (x *QuestCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *QuestCfg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuestCfg) GetQuestType() int32 {
	if x != nil {
		return x.QuestType
	}
	return 0
}

func (x *QuestCfg) GetRefreshType() int32 {
	if x != nil {
		return x.RefreshType
	}
	return 0
}

func (x *QuestCfg) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *QuestCfg) GetRewards() []*AddElemArg {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *QuestCfg) GetPreQuest() int32 {
	if x != nil {
		return x.PreQuest
	}
	return 0
}

func (x *QuestCfg) GetNextQuests() []int32 {
	if x != nil {
		return x.NextQuests
	}
	return nil
}

func (x *QuestCfg) GetConditions() []*ConditionCfg {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *QuestCfg) GetProgress() *ProgressCfg {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *QuestCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *QuestCfg) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *QuestCfg) GetPlayerLevel() int32 {
	if x != nil {
		return x.PlayerLevel
	}
	return 0
}

func (x *QuestCfg) GetCollects() []*ItemNum {
	if x != nil {
		return x.Collects
	}
	return nil
}

func (x *QuestCfg) GetConditionTemplates() []*CfgArgOptions {
	if x != nil {
		return x.ConditionTemplates
	}
	return nil
}

func (x *QuestCfg) GetProgressTemplate() *CfgArg {
	if x != nil {
		return x.ProgressTemplate
	}
	return nil
}

// 数值比较配置
type ValueCompareCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=Op,proto3" json:"Op,omitempty"`                 // 操作符 = > >= < <= != [] ![]
	Values        []int32                `protobuf:"varint,2,rep,packed,name=Values,proto3" json:"Values,omitempty"` // 比较的值(可配多个)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueCompareCfg) Reset() {
	*x = ValueCompareCfg{}
	mi := &file_cfg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueCompareCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueCompareCfg) ProtoMessage() {}

func (x *ValueCompareCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueCompareCfg.ProtoReflect.Descriptor instead.
func (*ValueCompareCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{10}
}

func (x *ValueCompareCfg) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ValueCompareCfg) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// 条件配置(ConditionTemplateCfg + Values + 可选Options)
type ConditionCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`                                                                                      // 条件类型(enum ConditionType)
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`                                                                                         // 关键字,如ConditionType_PlayerPropertyCompare对应的属性名
	Op            string                 `protobuf:"bytes,3,opt,name=Op,proto3" json:"Op,omitempty"`                                                                                           // 操作符 = > >= < <= != [] ![]
	Values        []int32                `protobuf:"varint,4,rep,packed,name=Values,proto3" json:"Values,omitempty"`                                                                           // 比较的值(可配多个)
	Options       []int32                `protobuf:"varint,5,rep,packed,name=Options,proto3" json:"Options,omitempty"`                                                                         // 可选参数(可配多个)
	Properties    map[string]string      `protobuf:"bytes,6,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	ClientCheck   bool                   `protobuf:"varint,7,opt,name=ClientCheck,proto3" json:"ClientCheck,omitempty"`                                                                        // 客户端是否可以直接判断条件,比如玩家的等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionCfg) Reset() {
	*x = ConditionCfg{}
	mi := &file_cfg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionCfg) ProtoMessage() {}

func (x *ConditionCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionCfg.ProtoReflect.Descriptor instead.
func (*ConditionCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{11}
}

func (x *ConditionCfg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ConditionCfg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConditionCfg) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ConditionCfg) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ConditionCfg) GetOptions() []int32 {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConditionCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ConditionCfg) GetClientCheck() bool {
	if x != nil {
		return x.ClientCheck
	}
	return false
}

// 条件模板配置
type ConditionTemplateCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,4,opt,name=CfgId,proto3" json:"CfgId,omitempty"`                                                                                    // 配置id
	Type          int32                  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`                                                                                      // 条件类型(enum ConditionType)
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`                                                                                         // 关键字,如ConditionType_PlayerPropertyCompare对应的属性名
	Op            string                 `protobuf:"bytes,3,opt,name=Op,proto3" json:"Op,omitempty"`                                                                                           // 操作符 = > >= < <= != [] ![]
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	ClientCheck   bool                   `protobuf:"varint,6,opt,name=ClientCheck,proto3" json:"ClientCheck,omitempty"`                                                                        // 客户端是否可以直接判断条件,比如玩家的等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionTemplateCfg) Reset() {
	*x = ConditionTemplateCfg{}
	mi := &file_cfg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionTemplateCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionTemplateCfg) ProtoMessage() {}

func (x *ConditionTemplateCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionTemplateCfg.ProtoReflect.Descriptor instead.
func (*ConditionTemplateCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{12}
}

func (x *ConditionTemplateCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ConditionTemplateCfg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ConditionTemplateCfg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConditionTemplateCfg) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ConditionTemplateCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ConditionTemplateCfg) GetClientCheck() bool {
	if x != nil {
		return x.ClientCheck
	}
	return false
}

// 进度配置(ProgressTemplateCfg + Total)
type ProgressCfg struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Type              int32                       `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`                                                                                                    // 进度类型(enum ProgressType)
	Total             int32                       `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`                                                                                                  // 总进度要求
	NeedInit          bool                        `protobuf:"varint,3,opt,name=NeedInit,proto3" json:"NeedInit,omitempty"`                                                                                            // 接任务时,是否初始化一下当前进度
	Event             string                      `protobuf:"bytes,4,opt,name=Event,proto3" json:"Event,omitempty"`                                                                                                   // 关联的事件名
	ProgressField     string                      `protobuf:"bytes,5,opt,name=ProgressField,proto3" json:"ProgressField,omitempty"`                                                                                   // 以事件字段值作为进度值,为空表示进度值是1
	IntEventFields    map[string]*ValueCompareCfg `protobuf:"bytes,6,rep,name=IntEventFields,proto3" json:"IntEventFields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // 数值类型的事件字段值(支持复杂的比较操作符)
	StringEventFields map[string]string           `protobuf:"bytes,7,rep,name=StringEventFields,proto3" json:"StringEventFields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 事件字段值(字符串形式)
	Properties        map[string]string           `protobuf:"bytes,8,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`               // 扩展属性
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProgressCfg) Reset() {
	*x = ProgressCfg{}
	mi := &file_cfg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressCfg) ProtoMessage() {}

func (x *ProgressCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressCfg.ProtoReflect.Descriptor instead.
func (*ProgressCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{13}
}

func (x *ProgressCfg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProgressCfg) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProgressCfg) GetNeedInit() bool {
	if x != nil {
		return x.NeedInit
	}
	return false
}

func (x *ProgressCfg) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ProgressCfg) GetProgressField() string {
	if x != nil {
		return x.ProgressField
	}
	return ""
}

func (x *ProgressCfg) GetIntEventFields() map[string]*ValueCompareCfg {
	if x != nil {
		return x.IntEventFields
	}
	return nil
}

func (x *ProgressCfg) GetStringEventFields() map[string]string {
	if x != nil {
		return x.StringEventFields
	}
	return nil
}

func (x *ProgressCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// 进度模板配置
type ProgressTemplateCfg struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	CfgId             int32                       `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`                                                                                                  // 配置id
	Type              int32                       `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`                                                                                                    // 进度类型(enum ProgressType)
	NeedInit          bool                        `protobuf:"varint,3,opt,name=NeedInit,proto3" json:"NeedInit,omitempty"`                                                                                            // 接任务时,是否初始化一下当前进度
	Event             string                      `protobuf:"bytes,4,opt,name=Event,proto3" json:"Event,omitempty"`                                                                                                   // 关联的事件名
	ProgressField     string                      `protobuf:"bytes,5,opt,name=ProgressField,proto3" json:"ProgressField,omitempty"`                                                                                   // 以事件字段值作为进度值,为空表示进度值是1
	IntEventFields    map[string]*ValueCompareCfg `protobuf:"bytes,6,rep,name=IntEventFields,proto3" json:"IntEventFields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // 数值类型的事件字段值(支持复杂的比较操作符)
	StringEventFields map[string]string           `protobuf:"bytes,7,rep,name=StringEventFields,proto3" json:"StringEventFields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 事件字段值(字符串形式)
	Properties        map[string]string           `protobuf:"bytes,8,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`               // 扩展属性
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProgressTemplateCfg) Reset() {
	*x = ProgressTemplateCfg{}
	mi := &file_cfg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressTemplateCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressTemplateCfg) ProtoMessage() {}

func (x *ProgressTemplateCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressTemplateCfg.ProtoReflect.Descriptor instead.
func (*ProgressTemplateCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{14}
}

func (x *ProgressTemplateCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ProgressTemplateCfg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProgressTemplateCfg) GetNeedInit() bool {
	if x != nil {
		return x.NeedInit
	}
	return false
}

func (x *ProgressTemplateCfg) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ProgressTemplateCfg) GetProgressField() string {
	if x != nil {
		return x.ProgressField
	}
	return ""
}

func (x *ProgressTemplateCfg) GetIntEventFields() map[string]*ValueCompareCfg {
	if x != nil {
		return x.IntEventFields
	}
	return nil
}

func (x *ProgressTemplateCfg) GetStringEventFields() map[string]string {
	if x != nil {
		return x.StringEventFields
	}
	return nil
}

func (x *ProgressTemplateCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// 兑换配置
type ExchangeCfg struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CfgId              int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Conditions         []*ConditionCfg        `protobuf:"bytes,2,rep,name=Conditions,proto3" json:"Conditions,omitempty"`                                                                           // 兑换条件
	Consumes           []*ItemNum             `protobuf:"bytes,3,rep,name=Consumes,proto3" json:"Consumes,omitempty"`                                                                               // 需要消耗的物品
	Rewards            []*AddElemArg          `protobuf:"bytes,4,rep,name=Rewards,proto3" json:"Rewards,omitempty"`                                                                                 // 获得物品
	CountLimit         int32                  `protobuf:"varint,5,opt,name=CountLimit,proto3" json:"CountLimit,omitempty"`                                                                          // 兑换次数限制(0表示无次数限制)
	RefreshType        int32                  `protobuf:"varint,6,opt,name=RefreshType,proto3" json:"RefreshType,omitempty"`                                                                        // 刷新机制(enum RefreshType)
	Category           int32                  `protobuf:"varint,7,opt,name=Category,proto3" json:"Category,omitempty"`                                                                              // 兑换分类(enum ExchangeCategory)
	Properties         map[string]string      `protobuf:"bytes,8,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	Detail             string                 `protobuf:"bytes,9,opt,name=Detail,proto3" json:"Detail,omitempty"`
	Icon               string                 `protobuf:"bytes,10,opt,name=Icon,proto3" json:"Icon,omitempty"`                             // 图标(客户端使用)
	ConditionTemplates []*CfgArgOptions       `protobuf:"bytes,21,rep,name=ConditionTemplates,proto3" json:"ConditionTemplates,omitempty"` // 关联的配置模板id和参数,简化配置表用,业务代码不要调用
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExchangeCfg) Reset() {
	*x = ExchangeCfg{}
	mi := &file_cfg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCfg) ProtoMessage() {}

func (x *ExchangeCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCfg.ProtoReflect.Descriptor instead.
func (*ExchangeCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{15}
}

func (x *ExchangeCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ExchangeCfg) GetConditions() []*ConditionCfg {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ExchangeCfg) GetConsumes() []*ItemNum {
	if x != nil {
		return x.Consumes
	}
	return nil
}

func (x *ExchangeCfg) GetRewards() []*AddElemArg {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *ExchangeCfg) GetCountLimit() int32 {
	if x != nil {
		return x.CountLimit
	}
	return 0
}

func (x *ExchangeCfg) GetRefreshType() int32 {
	if x != nil {
		return x.RefreshType
	}
	return 0
}

func (x *ExchangeCfg) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *ExchangeCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ExchangeCfg) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ExchangeCfg) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ExchangeCfg) GetConditionTemplates() []*CfgArgOptions {
	if x != nil {
		return x.ConditionTemplates
	}
	return nil
}

// 活动基础配置
type ActivityCfg struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CfgId             int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Detail            string                 `protobuf:"bytes,3,opt,name=Detail,proto3" json:"Detail,omitempty"`
	Template          string                 `protobuf:"bytes,4,opt,name=Template,proto3" json:"Template,omitempty"`                                                                                // 活动模板名
	RefreshType       int32                  `protobuf:"varint,5,opt,name=RefreshType,proto3" json:"RefreshType,omitempty"`                                                                         // 刷新机制(enum RefreshType)
	CycleType         int32                  `protobuf:"varint,6,opt,name=CycleType,proto3" json:"CycleType,omitempty"`                                                                             // 活动周期类型
	TimeType          int32                  `protobuf:"varint,7,opt,name=TimeType,proto3" json:"TimeType,omitempty"`                                                                               // 时间类型(enum TimeType)
	BeginTime         int32                  `protobuf:"varint,8,opt,name=BeginTime,proto3" json:"BeginTime,omitempty"`                                                                             // 开始时间(TimeType为TimeType_Timestamp时,格式是时间戳 TimeType为TimeType_Date时,格式是20240219)
	EndTime           int32                  `protobuf:"varint,9,opt,name=EndTime,proto3" json:"EndTime,omitempty"`                                                                                 // 结束时间(TimeType为TimeType_Timestamp时,格式是时间戳 TimeType为TimeType_Date时,格式是20240219)
	ExchangeIds       []int32                `protobuf:"varint,10,rep,packed,name=ExchangeIds,proto3" json:"ExchangeIds,omitempty"`                                                                 // 兑换配置
	IsOff             bool                   `protobuf:"varint,11,opt,name=IsOff,proto3" json:"IsOff,omitempty"`                                                                                    // 是否关闭
	RemoveDataWhenEnd bool                   `protobuf:"varint,12,opt,name=RemoveDataWhenEnd,proto3" json:"RemoveDataWhenEnd,omitempty"`                                                            // 活动结束时,是否删除活动数据
	MinPlayerLevel    int32                  `protobuf:"varint,14,opt,name=MinPlayerLevel,proto3" json:"MinPlayerLevel,omitempty"`                                                                  // 参与活动的最低玩家等级要求(0表示不限制)
	MaxPlayerLevel    int32                  `protobuf:"varint,15,opt,name=MaxPlayerLevel,proto3" json:"MaxPlayerLevel,omitempty"`                                                                  // 参与活动的最大玩家等级上限(0表示不限制)
	QuestIds          []int32                `protobuf:"varint,16,rep,packed,name=QuestIds,proto3" json:"QuestIds,omitempty"`                                                                       // 活动子任务id
	Properties        map[string]string      `protobuf:"bytes,17,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivityCfg) Reset() {
	*x = ActivityCfg{}
	mi := &file_cfg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityCfg) ProtoMessage() {}

func (x *ActivityCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityCfg.ProtoReflect.Descriptor instead.
func (*ActivityCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{16}
}

func (x *ActivityCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ActivityCfg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivityCfg) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ActivityCfg) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *ActivityCfg) GetRefreshType() int32 {
	if x != nil {
		return x.RefreshType
	}
	return 0
}

func (x *ActivityCfg) GetCycleType() int32 {
	if x != nil {
		return x.CycleType
	}
	return 0
}

func (x *ActivityCfg) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *ActivityCfg) GetBeginTime() int32 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *ActivityCfg) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ActivityCfg) GetExchangeIds() []int32 {
	if x != nil {
		return x.ExchangeIds
	}
	return nil
}

func (x *ActivityCfg) GetIsOff() bool {
	if x != nil {
		return x.IsOff
	}
	return false
}

func (x *ActivityCfg) GetRemoveDataWhenEnd() bool {
	if x != nil {
		return x.RemoveDataWhenEnd
	}
	return false
}

func (x *ActivityCfg) GetMinPlayerLevel() int32 {
	if x != nil {
		return x.MinPlayerLevel
	}
	return 0
}

func (x *ActivityCfg) GetMaxPlayerLevel() int32 {
	if x != nil {
		return x.MaxPlayerLevel
	}
	return 0
}

func (x *ActivityCfg) GetQuestIds() []int32 {
	if x != nil {
		return x.QuestIds
	}
	return nil
}

func (x *ActivityCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// 升级经验
type LevelExp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=Level,proto3" json:"Level,omitempty"`     // 等级
	NeedExp       int32                  `protobuf:"varint,2,opt,name=NeedExp,proto3" json:"NeedExp,omitempty"` // 升到该等级需要的经验值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelExp) Reset() {
	*x = LevelExp{}
	mi := &file_cfg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelExp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelExp) ProtoMessage() {}

func (x *LevelExp) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelExp.ProtoReflect.Descriptor instead.
func (*LevelExp) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{17}
}

func (x *LevelExp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LevelExp) GetNeedExp() int32 {
	if x != nil {
		return x.NeedExp
	}
	return 0
}

// 商店配置
type ShopCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`                                                                                    // 配置id
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                                                                                       // 商店名
	ExchangeIds   []int32                `protobuf:"varint,3,rep,packed,name=ExchangeIds,proto3" json:"ExchangeIds,omitempty"`                                                                 // 商店的每1个格子就是1个兑换礼包
	Properties    map[string]string      `protobuf:"bytes,8,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCfg) Reset() {
	*x = ShopCfg{}
	mi := &file_cfg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCfg) ProtoMessage() {}

func (x *ShopCfg) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCfg.ProtoReflect.Descriptor instead.
func (*ShopCfg) Descriptor() ([]byte, []int) {
	return file_cfg_proto_rawDescGZIP(), []int{18}
}

func (x *ShopCfg) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ShopCfg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopCfg) GetExchangeIds() []int32 {
	if x != nil {
		return x.ExchangeIds
	}
	return nil
}

func (x *ShopCfg) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_cfg_proto protoreflect.FileDescriptor

const file_cfg_proto_rawDesc = "" +
	"\n" +
	"\tcfg.proto\x12\agserver\"1\n" +
	"\aItemNum\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x05R\x03Num\"/\n" +
	"\aIdCount\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x05R\x05Count\"\x98\x03\n" +
	"\aItemCfg\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Detail\x18\x03 \x01(\tR\x06Detail\x12\x1a\n" +
	"\bItemType\x18\x04 \x01(\x05R\bItemType\x12\x18\n" +
	"\aSubType\x18\x05 \x01(\x05R\aSubType\x12\x1a\n" +
	"\bCategory\x18\x06 \x01(\x05R\bCategory\x12\x12\n" +
	"\x04Args\x18\a \x03(\x05R\x04Args\x12\x1a\n" +
	"\bTimeType\x18\b \x01(\x05R\bTimeType\x12\x18\n" +
	"\aTimeout\x18\t \x01(\x05R\aTimeout\x12\x1a\n" +
	"\bViewType\x18\n" +
	" \x01(\x05R\bViewType\x12@\n" +
	"\n" +
	"Properties\x18\v \x03(\v2 .gserver.ItemCfg.PropertiesEntryR\n" +
	"Properties\x12\x12\n" +
	"\x04Icon\x18\f \x01(\tR\x04Icon\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x02\n" +
	"\n" +
	"AddElemArg\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x05R\x03Num\x12\x1a\n" +
	"\bTimeType\x18\x03 \x01(\x05R\bTimeType\x12\x18\n" +
	"\aTimeout\x18\x04 \x01(\x05R\aTimeout\x12\x16\n" +
	"\x06Source\x18\x05 \x01(\x05R\x06Source\x12C\n" +
	"\n" +
	"Properties\x18\x06 \x03(\v2#.gserver.AddElemArg.PropertiesEntryR\n" +
	"Properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\n" +
	"DelElemArg\x12\x1a\n" +
	"\bUniqueId\x18\x01 \x01(\x03R\bUniqueId\x12\x14\n" +
	"\x05CfgId\x18\x02 \x01(\x05R\x05CfgId\x12\x10\n" +
	"\x03Num\x18\x03 \x01(\x05R\x03Num\x12\x16\n" +
	"\x06Source\x18\x04 \x01(\x05R\x06Source\x12C\n" +
	"\n" +
	"Properties\x18\x05 \x03(\v2#.gserver.DelElemArg.PropertiesEntryR\n" +
	"Properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x06CfgArg\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x10\n" +
	"\x03Arg\x18\x02 \x01(\x05R\x03Arg\"3\n" +
	"\aCfgArgs\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x12\n" +
	"\x04Args\x18\x02 \x03(\x05R\x04Args\"S\n" +
	"\rCfgArgOptions\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x12\n" +
	"\x04Args\x18\x02 \x03(\x05R\x04Args\x12\x18\n" +
	"\aOptions\x18\x03 \x03(\x05R\aOptions\"5\n" +
	"\tTypeValue\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x05R\x05Value\"\xd3\x05\n" +
	"\bQuestCfg\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\tQuestType\x18\x03 \x01(\x05R\tQuestType\x12 \n" +
	"\vRefreshType\x18\x04 \x01(\x05R\vRefreshType\x12\x1a\n" +
	"\bCategory\x18\x05 \x01(\x05R\bCategory\x12-\n" +
	"\aRewards\x18\x06 \x03(\v2\x13.gserver.AddElemArgR\aRewards\x12\x1a\n" +
	"\bPreQuest\x18\a \x01(\x05R\bPreQuest\x12\x1e\n" +
	"\n" +
	"NextQuests\x18\b \x03(\x05R\n" +
	"NextQuests\x125\n" +
	"\n" +
	"Conditions\x18\t \x03(\v2\x15.gserver.ConditionCfgR\n" +
	"Conditions\x120\n" +
	"\bProgress\x18\n" +
	" \x01(\v2\x14.gserver.ProgressCfgR\bProgress\x12A\n" +
	"\n" +
	"Properties\x18\v \x03(\v2!.gserver.QuestCfg.PropertiesEntryR\n" +
	"Properties\x12\x16\n" +
	"\x06Detail\x18\f \x01(\tR\x06Detail\x12 \n" +
	"\vPlayerLevel\x18\r \x01(\x05R\vPlayerLevel\x12,\n" +
	"\bCollects\x18\x0e \x03(\v2\x10.gserver.ItemNumR\bCollects\x12F\n" +
	"\x12ConditionTemplates\x18\x15 \x03(\v2\x16.gserver.CfgArgOptionsR\x12ConditionTemplates\x12;\n" +
	"\x10ProgressTemplate\x18\x16 \x01(\v2\x0f.gserver.CfgArgR\x10ProgressTemplate\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x0fValueCompareCfg\x12\x0e\n" +
	"\x02Op\x18\x01 \x01(\tR\x02Op\x12\x16\n" +
	"\x06Values\x18\x02 \x03(\x05R\x06Values\"\x9e\x02\n" +
	"\fConditionCfg\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x0e\n" +
	"\x02Op\x18\x03 \x01(\tR\x02Op\x12\x16\n" +
	"\x06Values\x18\x04 \x03(\x05R\x06Values\x12\x18\n" +
	"\aOptions\x18\x05 \x03(\x05R\aOptions\x12E\n" +
	"\n" +
	"Properties\x18\x06 \x03(\v2%.gserver.ConditionCfg.PropertiesEntryR\n" +
	"Properties\x12 \n" +
	"\vClientCheck\x18\a \x01(\bR\vClientCheck\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x02\n" +
	"\x14ConditionTemplateCfg\x12\x14\n" +
	"\x05CfgId\x18\x04 \x01(\x05R\x05CfgId\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x0e\n" +
	"\x02Op\x18\x03 \x01(\tR\x02Op\x12M\n" +
	"\n" +
	"Properties\x18\x05 \x03(\v2-.gserver.ConditionTemplateCfg.PropertiesEntryR\n" +
	"Properties\x12 \n" +
	"\vClientCheck\x18\x06 \x01(\bR\vClientCheck\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x04\n" +
	"\vProgressCfg\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x05R\x05Total\x12\x1a\n" +
	"\bNeedInit\x18\x03 \x01(\bR\bNeedInit\x12\x14\n" +
	"\x05Event\x18\x04 \x01(\tR\x05Event\x12$\n" +
	"\rProgressField\x18\x05 \x01(\tR\rProgressField\x12P\n" +
	"\x0eIntEventFields\x18\x06 \x03(\v2(.gserver.ProgressCfg.IntEventFieldsEntryR\x0eIntEventFields\x12Y\n" +
	"\x11StringEventFields\x18\a \x03(\v2+.gserver.ProgressCfg.StringEventFieldsEntryR\x11StringEventFields\x12D\n" +
	"\n" +
	"Properties\x18\b \x03(\v2$.gserver.ProgressCfg.PropertiesEntryR\n" +
	"Properties\x1a[\n" +
	"\x13IntEventFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.gserver.ValueCompareCfgR\x05value:\x028\x01\x1aD\n" +
	"\x16StringEventFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x05\n" +
	"\x13ProgressTemplateCfg\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x05R\x04Type\x12\x1a\n" +
	"\bNeedInit\x18\x03 \x01(\bR\bNeedInit\x12\x14\n" +
	"\x05Event\x18\x04 \x01(\tR\x05Event\x12$\n" +
	"\rProgressField\x18\x05 \x01(\tR\rProgressField\x12X\n" +
	"\x0eIntEventFields\x18\x06 \x03(\v20.gserver.ProgressTemplateCfg.IntEventFieldsEntryR\x0eIntEventFields\x12a\n" +
	"\x11StringEventFields\x18\a \x03(\v23.gserver.ProgressTemplateCfg.StringEventFieldsEntryR\x11StringEventFields\x12L\n" +
	"\n" +
	"Properties\x18\b \x03(\v2,.gserver.ProgressTemplateCfg.PropertiesEntryR\n" +
	"Properties\x1a[\n" +
	"\x13IntEventFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.gserver.ValueCompareCfgR\x05value:\x028\x01\x1aD\n" +
	"\x16StringEventFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x04\n" +
	"\vExchangeCfg\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x125\n" +
	"\n" +
	"Conditions\x18\x02 \x03(\v2\x15.gserver.ConditionCfgR\n" +
	"Conditions\x12,\n" +
	"\bConsumes\x18\x03 \x03(\v2\x10.gserver.ItemNumR\bConsumes\x12-\n" +
	"\aRewards\x18\x04 \x03(\v2\x13.gserver.AddElemArgR\aRewards\x12\x1e\n" +
	"\n" +
	"CountLimit\x18\x05 \x01(\x05R\n" +
	"CountLimit\x12 \n" +
	"\vRefreshType\x18\x06 \x01(\x05R\vRefreshType\x12\x1a\n" +
	"\bCategory\x18\a \x01(\x05R\bCategory\x12D\n" +
	"\n" +
	"Properties\x18\b \x03(\v2$.gserver.ExchangeCfg.PropertiesEntryR\n" +
	"Properties\x12\x16\n" +
	"\x06Detail\x18\t \x01(\tR\x06Detail\x12\x12\n" +
	"\x04Icon\x18\n" +
	" \x01(\tR\x04Icon\x12F\n" +
	"\x12ConditionTemplates\x18\x15 \x03(\v2\x16.gserver.CfgArgOptionsR\x12ConditionTemplates\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x04\n" +
	"\vActivityCfg\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Detail\x18\x03 \x01(\tR\x06Detail\x12\x1a\n" +
	"\bTemplate\x18\x04 \x01(\tR\bTemplate\x12 \n" +
	"\vRefreshType\x18\x05 \x01(\x05R\vRefreshType\x12\x1c\n" +
	"\tCycleType\x18\x06 \x01(\x05R\tCycleType\x12\x1a\n" +
	"\bTimeType\x18\a \x01(\x05R\bTimeType\x12\x1c\n" +
	"\tBeginTime\x18\b \x01(\x05R\tBeginTime\x12\x18\n" +
	"\aEndTime\x18\t \x01(\x05R\aEndTime\x12 \n" +
	"\vExchangeIds\x18\n" +
	" \x03(\x05R\vExchangeIds\x12\x14\n" +
	"\x05IsOff\x18\v \x01(\bR\x05IsOff\x12,\n" +
	"\x11RemoveDataWhenEnd\x18\f \x01(\bR\x11RemoveDataWhenEnd\x12&\n" +
	"\x0eMinPlayerLevel\x18\x0e \x01(\x05R\x0eMinPlayerLevel\x12&\n" +
	"\x0eMaxPlayerLevel\x18\x0f \x01(\x05R\x0eMaxPlayerLevel\x12\x1a\n" +
	"\bQuestIds\x18\x10 \x03(\x05R\bQuestIds\x12D\n" +
	"\n" +
	"Properties\x18\x11 \x03(\v2$.gserver.ActivityCfg.PropertiesEntryR\n" +
	"Properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\bLevelExp\x12\x14\n" +
	"\x05Level\x18\x01 \x01(\x05R\x05Level\x12\x18\n" +
	"\aNeedExp\x18\x02 \x01(\x05R\aNeedExp\"\xd6\x01\n" +
	"\aShopCfg\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vExchangeIds\x18\x03 \x03(\x05R\vExchangeIds\x12@\n" +
	"\n" +
	"Properties\x18\b \x03(\v2 .gserver.ShopCfg.PropertiesEntryR\n" +
	"Properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*i\n" +
	"\x05Color\x12\x0e\n" +
	"\n" +
	"Color_None\x10\x00\x12\r\n" +
	"\tColor_Red\x10\x01\x12\x0f\n" +
	"\vColor_Green\x10\x02\x12\x0e\n" +
	"\n" +
	"Color_Blue\x10\x03\x12\x10\n" +
	"\fColor_Yellow\x10\x04\x12\x0e\n" +
	"\n" +
	"Color_Gray\x10\x05*8\n" +
	"\vRefreshType\x12\x14\n" +
	"\x10RefreshType_None\x10\x00\x12\x13\n" +
	"\x0fRefreshType_Day\x10\x01*H\n" +
	"\bTimeType\x12\x11\n" +
	"\rTimeType_None\x10\x00\x12\x16\n" +
	"\x12TimeType_Timestamp\x10\x01\x12\x11\n" +
	"\rTimeType_Date\x10\x02*1\n" +
	"\bItemType\x12\x11\n" +
	"\rItemType_None\x10\x00\x12\x12\n" +
	"\x0eItemType_Equip\x10\x01*e\n" +
	"\vItemSubType\x12\x14\n" +
	"\x10ItemSubType_None\x10\x00\x12\x14\n" +
	"\x10ItemSubType_Gold\x10\x01\x12\x13\n" +
	"\x0fItemSubType_Exp\x10\x02\x12\x15\n" +
	"\x11ItemSubType_Quest\x10\x03*%\n" +
	"\fItemCategory\x12\x15\n" +
	"\x11ItemCategory_None\x10\x00*<\n" +
	"\fItemViewType\x12\x15\n" +
	"\x11ItemViewType_None\x10\x00\x12\x15\n" +
	"\x11ItemViewType_Hide\x10\x01**\n" +
	"\x06ItemId\x12\x0f\n" +
	"\vItemId_None\x10\x00\x12\x0f\n" +
	"\vItemId_Coin\x10\x01*R\n" +
	"\tQuestType\x12\x12\n" +
	"\x0eQuestType_None\x10\x00\x12\x16\n" +
	"\x12QuestType_SubQuest\x10\x01\x12\x19\n" +
	"\x15QuestType_Achievement\x10\x02*'\n" +
	"\rQuestCategory\x12\x16\n" +
	"\x12QuestCategory_None\x10\x00*H\n" +
	"\x10ExchangeCategory\x12\x19\n" +
	"\x15ExchangeCategory_None\x10\x00\x12\x19\n" +
	"\x15ExchangeCategory_Shop\x10\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_cfg_proto_rawDescOnce sync.Once
	file_cfg_proto_rawDescData []byte
)

func file_cfg_proto_rawDescGZIP() []byte {
	file_cfg_proto_rawDescOnce.Do(func() {
		file_cfg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cfg_proto_rawDesc), len(file_cfg_proto_rawDesc)))
	})
	return file_cfg_proto_rawDescData
}

var file_cfg_proto_enumTypes = make([]protoimpl.EnumInfo, 11)
var file_cfg_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_cfg_proto_goTypes = []any{
	(Color)(0),                   // 0: gserver.Color
	(RefreshType)(0),             // 1: gserver.RefreshType
	(TimeType)(0),                // 2: gserver.TimeType
	(ItemType)(0),                // 3: gserver.ItemType
	(ItemSubType)(0),             // 4: gserver.ItemSubType
	(ItemCategory)(0),            // 5: gserver.ItemCategory
	(ItemViewType)(0),            // 6: gserver.ItemViewType
	(ItemId)(0),                  // 7: gserver.ItemId
	(QuestType)(0),               // 8: gserver.QuestType
	(QuestCategory)(0),           // 9: gserver.QuestCategory
	(ExchangeCategory)(0),        // 10: gserver.ExchangeCategory
	(*ItemNum)(nil),              // 11: gserver.ItemNum
	(*IdCount)(nil),              // 12: gserver.IdCount
	(*ItemCfg)(nil),              // 13: gserver.ItemCfg
	(*AddElemArg)(nil),           // 14: gserver.AddElemArg
	(*DelElemArg)(nil),           // 15: gserver.DelElemArg
	(*CfgArg)(nil),               // 16: gserver.CfgArg
	(*CfgArgs)(nil),              // 17: gserver.CfgArgs
	(*CfgArgOptions)(nil),        // 18: gserver.CfgArgOptions
	(*TypeValue)(nil),            // 19: gserver.TypeValue
	(*QuestCfg)(nil),             // 20: gserver.QuestCfg
	(*ValueCompareCfg)(nil),      // 21: gserver.ValueCompareCfg
	(*ConditionCfg)(nil),         // 22: gserver.ConditionCfg
	(*ConditionTemplateCfg)(nil), // 23: gserver.ConditionTemplateCfg
	(*ProgressCfg)(nil),          // 24: gserver.ProgressCfg
	(*ProgressTemplateCfg)(nil),  // 25: gserver.ProgressTemplateCfg
	(*ExchangeCfg)(nil),          // 26: gserver.ExchangeCfg
	(*ActivityCfg)(nil),          // 27: gserver.ActivityCfg
	(*LevelExp)(nil),             // 28: gserver.LevelExp
	(*ShopCfg)(nil),              // 29: gserver.ShopCfg
	nil,                          // 30: gserver.ItemCfg.PropertiesEntry
	nil,                          // 31: gserver.AddElemArg.PropertiesEntry
	nil,                          // 32: gserver.DelElemArg.PropertiesEntry
	nil,                          // 33: gserver.QuestCfg.PropertiesEntry
	nil,                          // 34: gserver.ConditionCfg.PropertiesEntry
	nil,                          // 35: gserver.ConditionTemplateCfg.PropertiesEntry
	nil,                          // 36: gserver.ProgressCfg.IntEventFieldsEntry
	nil,                          // 37: gserver.ProgressCfg.StringEventFieldsEntry
	nil,                          // 38: gserver.ProgressCfg.PropertiesEntry
	nil,                          // 39: gserver.ProgressTemplateCfg.IntEventFieldsEntry
	nil,                          // 40: gserver.ProgressTemplateCfg.StringEventFieldsEntry
	nil,                          // 41: gserver.ProgressTemplateCfg.PropertiesEntry
	nil,                          // 42: gserver.ExchangeCfg.PropertiesEntry
	nil,                          // 43: gserver.ActivityCfg.PropertiesEntry
	nil,                          // 44: gserver.ShopCfg.PropertiesEntry
}
var file_cfg_proto_depIdxs = []int32{
	30, // 0: gserver.ItemCfg.Properties:type_name -> gserver.ItemCfg.PropertiesEntry
	31, // 1: gserver.AddElemArg.Properties:type_name -> gserver.AddElemArg.PropertiesEntry
	32, // 2: gserver.DelElemArg.Properties:type_name -> gserver.DelElemArg.PropertiesEntry
	14, // 3: gserver.QuestCfg.Rewards:type_name -> gserver.AddElemArg
	22, // 4: gserver.QuestCfg.Conditions:type_name -> gserver.ConditionCfg
	24, // 5: gserver.QuestCfg.Progress:type_name -> gserver.ProgressCfg
	33, // 6: gserver.QuestCfg.Properties:type_name -> gserver.QuestCfg.PropertiesEntry
	11, // 7: gserver.QuestCfg.Collects:type_name -> gserver.ItemNum
	18, // 8: gserver.QuestCfg.ConditionTemplates:type_name -> gserver.CfgArgOptions
	16, // 9: gserver.QuestCfg.ProgressTemplate:type_name -> gserver.CfgArg
	34, // 10: gserver.ConditionCfg.Properties:type_name -> gserver.ConditionCfg.PropertiesEntry
	35, // 11: gserver.ConditionTemplateCfg.Properties:type_name -> gserver.ConditionTemplateCfg.PropertiesEntry
	36, // 12: gserver.ProgressCfg.IntEventFields:type_name -> gserver.ProgressCfg.IntEventFieldsEntry
	37, // 13: gserver.ProgressCfg.StringEventFields:type_name -> gserver.ProgressCfg.StringEventFieldsEntry
	38, // 14: gserver.ProgressCfg.Properties:type_name -> gserver.ProgressCfg.PropertiesEntry
	39, // 15: gserver.ProgressTemplateCfg.IntEventFields:type_name -> gserver.ProgressTemplateCfg.IntEventFieldsEntry
	40, // 16: gserver.ProgressTemplateCfg.StringEventFields:type_name -> gserver.ProgressTemplateCfg.StringEventFieldsEntry
	41, // 17: gserver.ProgressTemplateCfg.Properties:type_name -> gserver.ProgressTemplateCfg.PropertiesEntry
	22, // 18: gserver.ExchangeCfg.Conditions:type_name -> gserver.ConditionCfg
	11, // 19: gserver.ExchangeCfg.Consumes:type_name -> gserver.ItemNum
	14, // 20: gserver.ExchangeCfg.Rewards:type_name -> gserver.AddElemArg
	42, // 21: gserver.ExchangeCfg.Properties:type_name -> gserver.ExchangeCfg.PropertiesEntry
	18, // 22: gserver.ExchangeCfg.ConditionTemplates:type_name -> gserver.CfgArgOptions
	43, // 23: gserver.ActivityCfg.Properties:type_name -> gserver.ActivityCfg.PropertiesEntry
	44, // 24: gserver.ShopCfg.Properties:type_name -> gserver.ShopCfg.PropertiesEntry
	21, // 25: gserver.ProgressCfg.IntEventFieldsEntry.value:type_name -> gserver.ValueCompareCfg
	21, // 26: gserver.ProgressTemplateCfg.IntEventFieldsEntry.value:type_name -> gserver.ValueCompareCfg
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_cfg_proto_init() }
func file_cfg_proto_init() {
	if File_cfg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cfg_proto_rawDesc), len(file_cfg_proto_rawDesc)),
			NumEnums:      11,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cfg_proto_goTypes,
		DependencyIndexes: file_cfg_proto_depIdxs,
		EnumInfos:         file_cfg_proto_enumTypes,
		MessageInfos:      file_cfg_proto_msgTypes,
	}.Build()
	File_cfg_proto = out.File
	file_cfg_proto_goTypes = nil
	file_cfg_proto_depIdxs = nil
}
