// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: client_base.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 心跳包请求
type HeartBeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 请求方的时间戳(毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatReq) Reset() {
	*x = HeartBeatReq{}
	mi := &file_client_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatReq) ProtoMessage() {}

func (x *HeartBeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatReq.ProtoReflect.Descriptor instead.
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return file_client_base_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeatReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 心跳包回复
type HeartBeatRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestTimestamp  int64                  `protobuf:"varint,1,opt,name=requestTimestamp,proto3" json:"requestTimestamp,omitempty"`   // 请求方的时间戳(毫秒)
	ResponseTimestamp int64                  `protobuf:"varint,2,opt,name=responseTimestamp,proto3" json:"responseTimestamp,omitempty"` // 回复方的时间戳(毫秒)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartBeatRes) Reset() {
	*x = HeartBeatRes{}
	mi := &file_client_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRes) ProtoMessage() {}

func (x *HeartBeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRes.ProtoReflect.Descriptor instead.
func (*HeartBeatRes) Descriptor() ([]byte, []int) {
	return file_client_base_proto_rawDescGZIP(), []int{1}
}

func (x *HeartBeatRes) GetRequestTimestamp() int64 {
	if x != nil {
		return x.RequestTimestamp
	}
	return 0
}

func (x *HeartBeatRes) GetResponseTimestamp() int64 {
	if x != nil {
		return x.ResponseTimestamp
	}
	return 0
}

// 通用的错误返回消息
type ErrorRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       int32                  `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`    // 消息号
	ResultId      int32                  `protobuf:"varint,2,opt,name=resultId,proto3" json:"resultId,omitempty"`  // 错误信息id
	ResultStr     string                 `protobuf:"bytes,3,opt,name=resultStr,proto3" json:"resultStr,omitempty"` // 错误信息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorRes) Reset() {
	*x = ErrorRes{}
	mi := &file_client_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRes) ProtoMessage() {}

func (x *ErrorRes) ProtoReflect() protoreflect.Message {
	mi := &file_client_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRes.ProtoReflect.Descriptor instead.
func (*ErrorRes) Descriptor() ([]byte, []int) {
	return file_client_base_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorRes) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *ErrorRes) GetResultId() int32 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

func (x *ErrorRes) GetResultStr() string {
	if x != nil {
		return x.ResultStr
	}
	return ""
}

// 网关转发客户端消息到其他服务器,发生错误
type GateRouteClientPacketError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Command       int32                  `protobuf:"varint,2,opt,name=command,proto3" json:"command,omitempty"`    // 消息号
	ResultId      int32                  `protobuf:"varint,3,opt,name=resultId,proto3" json:"resultId,omitempty"`  // 错误信息id
	ResultStr     string                 `protobuf:"bytes,4,opt,name=resultStr,proto3" json:"resultStr,omitempty"` // 错误信息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateRouteClientPacketError) Reset() {
	*x = GateRouteClientPacketError{}
	mi := &file_client_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateRouteClientPacketError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRouteClientPacketError) ProtoMessage() {}

func (x *GateRouteClientPacketError) ProtoReflect() protoreflect.Message {
	mi := &file_client_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRouteClientPacketError.ProtoReflect.Descriptor instead.
func (*GateRouteClientPacketError) Descriptor() ([]byte, []int) {
	return file_client_base_proto_rawDescGZIP(), []int{3}
}

func (x *GateRouteClientPacketError) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GateRouteClientPacketError) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *GateRouteClientPacketError) GetResultId() int32 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

func (x *GateRouteClientPacketError) GetResultStr() string {
	if x != nil {
		return x.ResultStr
	}
	return ""
}

var File_client_base_proto protoreflect.FileDescriptor

const file_client_base_proto_rawDesc = "" +
	"\n" +
	"\x11client_base.proto\x12\agserver\",\n" +
	"\fHeartBeatReq\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"h\n" +
	"\fHeartBeatRes\x12*\n" +
	"\x10requestTimestamp\x18\x01 \x01(\x03R\x10requestTimestamp\x12,\n" +
	"\x11responseTimestamp\x18\x02 \x01(\x03R\x11responseTimestamp\"^\n" +
	"\bErrorRes\x12\x18\n" +
	"\acommand\x18\x01 \x01(\x05R\acommand\x12\x1a\n" +
	"\bresultId\x18\x02 \x01(\x05R\bresultId\x12\x1c\n" +
	"\tresultStr\x18\x03 \x01(\tR\tresultStr\"\x8c\x01\n" +
	"\x1aGateRouteClientPacketError\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x03R\bplayerId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\x05R\acommand\x12\x1a\n" +
	"\bresultId\x18\x03 \x01(\x05R\bresultId\x12\x1c\n" +
	"\tresultStr\x18\x04 \x01(\tR\tresultStrB\x06Z\x04./pbb\x06proto3"

var (
	file_client_base_proto_rawDescOnce sync.Once
	file_client_base_proto_rawDescData []byte
)

func file_client_base_proto_rawDescGZIP() []byte {
	file_client_base_proto_rawDescOnce.Do(func() {
		file_client_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_base_proto_rawDesc), len(file_client_base_proto_rawDesc)))
	})
	return file_client_base_proto_rawDescData
}

var file_client_base_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_client_base_proto_goTypes = []any{
	(*HeartBeatReq)(nil),               // 0: gserver.HeartBeatReq
	(*HeartBeatRes)(nil),               // 1: gserver.HeartBeatRes
	(*ErrorRes)(nil),                   // 2: gserver.ErrorRes
	(*GateRouteClientPacketError)(nil), // 3: gserver.GateRouteClientPacketError
}
var file_client_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_base_proto_init() }
func file_client_base_proto_init() {
	if File_client_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_base_proto_rawDesc), len(file_client_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_base_proto_goTypes,
		DependencyIndexes: file_client_base_proto_depIdxs,
		MessageInfos:      file_client_base_proto_msgTypes,
	}.Build()
	File_client_base_proto = out.File
	file_client_base_proto_goTypes = nil
	file_client_base_proto_depIdxs = nil
}
