// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: exchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 同步兑换数据给客户端
type ExchangeSync struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Records       map[int32]*ExchangeRecord `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeSync) Reset() {
	*x = ExchangeSync{}
	mi := &file_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeSync) ProtoMessage() {}

func (x *ExchangeSync) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeSync.ProtoReflect.Descriptor instead.
func (*ExchangeSync) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeSync) GetRecords() map[int32]*ExchangeRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// 兑换数据更新
type ExchangeUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ExchangeRecord      `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"` // 兑换数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeUpdate) Reset() {
	*x = ExchangeUpdate{}
	mi := &file_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeUpdate) ProtoMessage() {}

func (x *ExchangeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeUpdate.ProtoReflect.Descriptor instead.
func (*ExchangeUpdate) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeUpdate) GetRecords() []*ExchangeRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// 兑换数据删除
type ExchangeRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgIds        []int32                `protobuf:"varint,1,rep,packed,name=CfgIds,proto3" json:"CfgIds,omitempty"` // 兑换配置id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRemove) Reset() {
	*x = ExchangeRemove{}
	mi := &file_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRemove) ProtoMessage() {}

func (x *ExchangeRemove) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRemove.ProtoReflect.Descriptor instead.
func (*ExchangeRemove) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRemove) GetCfgIds() []int32 {
	if x != nil {
		return x.CfgIds
	}
	return nil
}

// 兑换请求req
type ExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdCounts      []*IdCount             `protobuf:"bytes,1,rep,name=IdCounts,proto3" json:"IdCounts,omitempty"` // 支持批量兑换
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeReq) Reset() {
	*x = ExchangeReq{}
	mi := &file_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeReq) ProtoMessage() {}

func (x *ExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeReq.ProtoReflect.Descriptor instead.
func (*ExchangeReq) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeReq) GetIdCounts() []*IdCount {
	if x != nil {
		return x.IdCounts
	}
	return nil
}

// 兑换请求res
type ExchangeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdCounts      []*IdCount             `protobuf:"bytes,1,rep,name=IdCounts,proto3" json:"IdCounts,omitempty"` // 兑换请求数据
	Records       []*ExchangeRecord      `protobuf:"bytes,2,rep,name=Records,proto3" json:"Records,omitempty"`   // 当前兑换记录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRes) Reset() {
	*x = ExchangeRes{}
	mi := &file_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRes) ProtoMessage() {}

func (x *ExchangeRes) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRes.ProtoReflect.Descriptor instead.
func (*ExchangeRes) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeRes) GetIdCounts() []*IdCount {
	if x != nil {
		return x.IdCounts
	}
	return nil
}

func (x *ExchangeRes) GetRecords() []*ExchangeRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_exchange_proto protoreflect.FileDescriptor

const file_exchange_proto_rawDesc = "" +
	"\n" +
	"\x0eexchange.proto\x12\agserver\x1a\tcfg.proto\x1a\fplayer.proto\"\xa1\x01\n" +
	"\fExchangeSync\x12<\n" +
	"\aRecords\x18\x01 \x03(\v2\".gserver.ExchangeSync.RecordsEntryR\aRecords\x1aS\n" +
	"\fRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.gserver.ExchangeRecordR\x05value:\x028\x01\"C\n" +
	"\x0eExchangeUpdate\x121\n" +
	"\aRecords\x18\x01 \x03(\v2\x17.gserver.ExchangeRecordR\aRecords\"(\n" +
	"\x0eExchangeRemove\x12\x16\n" +
	"\x06CfgIds\x18\x01 \x03(\x05R\x06CfgIds\";\n" +
	"\vExchangeReq\x12,\n" +
	"\bIdCounts\x18\x01 \x03(\v2\x10.gserver.IdCountR\bIdCounts\"n\n" +
	"\vExchangeRes\x12,\n" +
	"\bIdCounts\x18\x01 \x03(\v2\x10.gserver.IdCountR\bIdCounts\x121\n" +
	"\aRecords\x18\x02 \x03(\v2\x17.gserver.ExchangeRecordR\aRecordsB\x06Z\x04./pbb\x06proto3"

var (
	file_exchange_proto_rawDescOnce sync.Once
	file_exchange_proto_rawDescData []byte
)

func file_exchange_proto_rawDescGZIP() []byte {
	file_exchange_proto_rawDescOnce.Do(func() {
		file_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)))
	})
	return file_exchange_proto_rawDescData
}

var file_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_exchange_proto_goTypes = []any{
	(*ExchangeSync)(nil),   // 0: gserver.ExchangeSync
	(*ExchangeUpdate)(nil), // 1: gserver.ExchangeUpdate
	(*ExchangeRemove)(nil), // 2: gserver.ExchangeRemove
	(*ExchangeReq)(nil),    // 3: gserver.ExchangeReq
	(*ExchangeRes)(nil),    // 4: gserver.ExchangeRes
	nil,                    // 5: gserver.ExchangeSync.RecordsEntry
	(*ExchangeRecord)(nil), // 6: gserver.ExchangeRecord
	(*IdCount)(nil),        // 7: gserver.IdCount
}
var file_exchange_proto_depIdxs = []int32{
	5, // 0: gserver.ExchangeSync.Records:type_name -> gserver.ExchangeSync.RecordsEntry
	6, // 1: gserver.ExchangeUpdate.Records:type_name -> gserver.ExchangeRecord
	7, // 2: gserver.ExchangeReq.IdCounts:type_name -> gserver.IdCount
	7, // 3: gserver.ExchangeRes.IdCounts:type_name -> gserver.IdCount
	6, // 4: gserver.ExchangeRes.Records:type_name -> gserver.ExchangeRecord
	6, // 5: gserver.ExchangeSync.RecordsEntry.value:type_name -> gserver.ExchangeRecord
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_exchange_proto_init() }
func file_exchange_proto_init() {
	if File_exchange_proto != nil {
		return
	}
	file_cfg_proto_init()
	file_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exchange_proto_goTypes,
		DependencyIndexes: file_exchange_proto_depIdxs,
		MessageInfos:      file_exchange_proto_msgTypes,
	}.Build()
	File_exchange_proto = out.File
	file_exchange_proto_goTypes = nil
	file_exchange_proto_depIdxs = nil
}
