// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.1
// source: global_entity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 进程统计信息
type ProcessStatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastStartupTimestamp  int64 `protobuf:"varint,1,opt,name=lastStartupTimestamp,proto3" json:"lastStartupTimestamp,omitempty"`   // 最近一次进程启动时间戳
	LastShutdownTimestamp int64 `protobuf:"varint,2,opt,name=lastShutdownTimestamp,proto3" json:"lastShutdownTimestamp,omitempty"` // 最近一次进程关闭时间戳
	LastUpdateDate        int32 `protobuf:"varint,3,opt,name=lastUpdateDate,proto3" json:"lastUpdateDate,omitempty"`               // 上次刷新日期,格式:yyyymmdd
}

func (x *ProcessStatInfo) Reset() {
	*x = ProcessStatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessStatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatInfo) ProtoMessage() {}

func (x *ProcessStatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_global_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatInfo.ProtoReflect.Descriptor instead.
func (*ProcessStatInfo) Descriptor() ([]byte, []int) {
	return file_global_entity_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessStatInfo) GetLastStartupTimestamp() int64 {
	if x != nil {
		return x.LastStartupTimestamp
	}
	return 0
}

func (x *ProcessStatInfo) GetLastShutdownTimestamp() int64 {
	if x != nil {
		return x.LastShutdownTimestamp
	}
	return 0
}

func (x *ProcessStatInfo) GetLastUpdateDate() int32 {
	if x != nil {
		return x.LastUpdateDate
	}
	return 0
}

// GlobalEntity在mongo中的保存格式
// 用于一次性把数据加载进来
type GlobalEntityData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key             string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ProcessStatInfo *ProcessStatInfo `protobuf:"bytes,2,opt,name=processStatInfo,proto3" json:"processStatInfo,omitempty"`
}

func (x *GlobalEntityData) Reset() {
	*x = GlobalEntityData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalEntityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalEntityData) ProtoMessage() {}

func (x *GlobalEntityData) ProtoReflect() protoreflect.Message {
	mi := &file_global_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalEntityData.ProtoReflect.Descriptor instead.
func (*GlobalEntityData) Descriptor() ([]byte, []int) {
	return file_global_entity_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalEntityData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GlobalEntityData) GetProcessStatInfo() *ProcessStatInfo {
	if x != nil {
		return x.ProcessStatInfo
	}
	return nil
}

type StartupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *StartupReq) Reset() {
	*x = StartupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartupReq) ProtoMessage() {}

func (x *StartupReq) ProtoReflect() protoreflect.Message {
	mi := &file_global_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartupReq.ProtoReflect.Descriptor instead.
func (*StartupReq) Descriptor() ([]byte, []int) {
	return file_global_entity_proto_rawDescGZIP(), []int{2}
}

func (x *StartupReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ShutdownReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ShutdownReq) Reset() {
	*x = ShutdownReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReq) ProtoMessage() {}

func (x *ShutdownReq) ProtoReflect() protoreflect.Message {
	mi := &file_global_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReq.ProtoReflect.Descriptor instead.
func (*ShutdownReq) Descriptor() ([]byte, []int) {
	return file_global_entity_proto_rawDescGZIP(), []int{3}
}

func (x *ShutdownReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_global_entity_proto protoreflect.FileDescriptor

var file_global_entity_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xa3,
	0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x32, 0x0a, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75,
	0x70, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x34, 0x0a, 0x15, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x68, 0x75, 0x74, 0x64,
	0x6f, 0x77, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x26, 0x0a, 0x0e,
	0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x22, 0x68, 0x0a, 0x10, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x42, 0x0a, 0x0f, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2a,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2b, 0x0a, 0x0b, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_global_entity_proto_rawDescOnce sync.Once
	file_global_entity_proto_rawDescData = file_global_entity_proto_rawDesc
)

func file_global_entity_proto_rawDescGZIP() []byte {
	file_global_entity_proto_rawDescOnce.Do(func() {
		file_global_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_entity_proto_rawDescData)
	})
	return file_global_entity_proto_rawDescData
}

var file_global_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_global_entity_proto_goTypes = []interface{}{
	(*ProcessStatInfo)(nil),  // 0: gserver.ProcessStatInfo
	(*GlobalEntityData)(nil), // 1: gserver.GlobalEntityData
	(*StartupReq)(nil),       // 2: gserver.StartupReq
	(*ShutdownReq)(nil),      // 3: gserver.ShutdownReq
}
var file_global_entity_proto_depIdxs = []int32{
	0, // 0: gserver.GlobalEntityData.processStatInfo:type_name -> gserver.ProcessStatInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_global_entity_proto_init() }
func file_global_entity_proto_init() {
	if File_global_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_global_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessStatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalEntityData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_entity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_entity_proto_goTypes,
		DependencyIndexes: file_global_entity_proto_depIdxs,
		MessageInfos:      file_global_entity_proto_msgTypes,
	}.Build()
	File_global_entity_proto = out.File
	file_global_entity_proto_rawDesc = nil
	file_global_entity_proto_goTypes = nil
	file_global_entity_proto_depIdxs = nil
}
