// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: global_entity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 进程统计信息
type ProcessStatInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LastStartupTimestamp  int64                  `protobuf:"varint,1,opt,name=lastStartupTimestamp,proto3" json:"lastStartupTimestamp,omitempty"`   // 最近一次进程启动时间戳
	LastShutdownTimestamp int64                  `protobuf:"varint,2,opt,name=lastShutdownTimestamp,proto3" json:"lastShutdownTimestamp,omitempty"` // 最近一次进程关闭时间戳
	LastUpdateDate        int32                  `protobuf:"varint,3,opt,name=lastUpdateDate,proto3" json:"lastUpdateDate,omitempty"`               // 上次刷新日期,格式:yyyymmdd
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ProcessStatInfo) Reset() {
	*x = ProcessStatInfo{}
	mi := &file_global_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatInfo) ProtoMessage() {}

func (x *ProcessStatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_global_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatInfo.ProtoReflect.Descriptor instead.
func (*ProcessStatInfo) Descriptor() ([]byte, []int) {
	return file_global_entity_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessStatInfo) GetLastStartupTimestamp() int64 {
	if x != nil {
		return x.LastStartupTimestamp
	}
	return 0
}

func (x *ProcessStatInfo) GetLastShutdownTimestamp() int64 {
	if x != nil {
		return x.LastShutdownTimestamp
	}
	return 0
}

func (x *ProcessStatInfo) GetLastUpdateDate() int32 {
	if x != nil {
		return x.LastUpdateDate
	}
	return 0
}

// GlobalEntity在mongo中的保存格式
// 用于一次性把数据加载进来
type GlobalEntityData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ProcessStatInfo *ProcessStatInfo       `protobuf:"bytes,2,opt,name=processStatInfo,proto3" json:"processStatInfo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GlobalEntityData) Reset() {
	*x = GlobalEntityData{}
	mi := &file_global_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalEntityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalEntityData) ProtoMessage() {}

func (x *GlobalEntityData) ProtoReflect() protoreflect.Message {
	mi := &file_global_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalEntityData.ProtoReflect.Descriptor instead.
func (*GlobalEntityData) Descriptor() ([]byte, []int) {
	return file_global_entity_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalEntityData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GlobalEntityData) GetProcessStatInfo() *ProcessStatInfo {
	if x != nil {
		return x.ProcessStatInfo
	}
	return nil
}

type StartupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartupReq) Reset() {
	*x = StartupReq{}
	mi := &file_global_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartupReq) ProtoMessage() {}

func (x *StartupReq) ProtoReflect() protoreflect.Message {
	mi := &file_global_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartupReq.ProtoReflect.Descriptor instead.
func (*StartupReq) Descriptor() ([]byte, []int) {
	return file_global_entity_proto_rawDescGZIP(), []int{2}
}

func (x *StartupReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ShutdownReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReq) Reset() {
	*x = ShutdownReq{}
	mi := &file_global_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReq) ProtoMessage() {}

func (x *ShutdownReq) ProtoReflect() protoreflect.Message {
	mi := &file_global_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReq.ProtoReflect.Descriptor instead.
func (*ShutdownReq) Descriptor() ([]byte, []int) {
	return file_global_entity_proto_rawDescGZIP(), []int{3}
}

func (x *ShutdownReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_global_entity_proto protoreflect.FileDescriptor

const file_global_entity_proto_rawDesc = "" +
	"\n" +
	"\x13global_entity.proto\x12\agserver\"\xa3\x01\n" +
	"\x0fProcessStatInfo\x122\n" +
	"\x14lastStartupTimestamp\x18\x01 \x01(\x03R\x14lastStartupTimestamp\x124\n" +
	"\x15lastShutdownTimestamp\x18\x02 \x01(\x03R\x15lastShutdownTimestamp\x12&\n" +
	"\x0elastUpdateDate\x18\x03 \x01(\x05R\x0elastUpdateDate\"h\n" +
	"\x10GlobalEntityData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12B\n" +
	"\x0fprocessStatInfo\x18\x02 \x01(\v2\x18.gserver.ProcessStatInfoR\x0fprocessStatInfo\"*\n" +
	"\n" +
	"StartupReq\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"+\n" +
	"\vShutdownReq\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestampB\x06Z\x04./pbb\x06proto3"

var (
	file_global_entity_proto_rawDescOnce sync.Once
	file_global_entity_proto_rawDescData []byte
)

func file_global_entity_proto_rawDescGZIP() []byte {
	file_global_entity_proto_rawDescOnce.Do(func() {
		file_global_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_global_entity_proto_rawDesc), len(file_global_entity_proto_rawDesc)))
	})
	return file_global_entity_proto_rawDescData
}

var file_global_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_global_entity_proto_goTypes = []any{
	(*ProcessStatInfo)(nil),  // 0: gserver.ProcessStatInfo
	(*GlobalEntityData)(nil), // 1: gserver.GlobalEntityData
	(*StartupReq)(nil),       // 2: gserver.StartupReq
	(*ShutdownReq)(nil),      // 3: gserver.ShutdownReq
}
var file_global_entity_proto_depIdxs = []int32{
	0, // 0: gserver.GlobalEntityData.processStatInfo:type_name -> gserver.ProcessStatInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_global_entity_proto_init() }
func file_global_entity_proto_init() {
	if File_global_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_global_entity_proto_rawDesc), len(file_global_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_entity_proto_goTypes,
		DependencyIndexes: file_global_entity_proto_depIdxs,
		MessageInfos:      file_global_entity_proto_msgTypes,
	}.Build()
	File_global_entity_proto = out.File
	file_global_entity_proto_goTypes = nil
	file_global_entity_proto_depIdxs = nil
}
