// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 账号登录请求
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"` // 客户端版本号,如0.0.0.1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 账号登录回复
type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	LoginSession  string                 `protobuf:"bytes,3,opt,name=LoginSession,proto3" json:"LoginSession,omitempty"` // 账号验证成功后的缓存session
	GameServer    *GameServerInfo        `protobuf:"bytes,4,opt,name=GameServer,proto3" json:"GameServer,omitempty"`     // 游戏服信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRes) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *LoginRes) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LoginRes) GetLoginSession() string {
	if x != nil {
		return x.LoginSession
	}
	return ""
}

func (x *LoginRes) GetGameServer() *GameServerInfo {
	if x != nil {
		return x.GameServer
	}
	return nil
}

// 注册账号
type AccountReg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountReg) Reset() {
	*x = AccountReg{}
	mi := &file_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReg) ProtoMessage() {}

func (x *AccountReg) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReg.ProtoReflect.Descriptor instead.
func (*AccountReg) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{2}
}

func (x *AccountReg) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountReg) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 注册账号回复
type AccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRes) Reset() {
	*x = AccountRes{}
	mi := &file_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRes) ProtoMessage() {}

func (x *AccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRes.ProtoReflect.Descriptor instead.
func (*AccountRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{3}
}

func (x *AccountRes) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountRes) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 游戏服务器信息
type GameServerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         int32                  `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`                // 服务器编号
	ClientListenAddr string                 `protobuf:"bytes,2,opt,name=ClientListenAddr,proto3" json:"ClientListenAddr,omitempty"` // 游戏服监听客户端地址
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameServerInfo) Reset() {
	*x = GameServerInfo{}
	mi := &file_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServerInfo) ProtoMessage() {}

func (x *GameServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServerInfo.ProtoReflect.Descriptor instead.
func (*GameServerInfo) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{4}
}

func (x *GameServerInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *GameServerInfo) GetClientListenAddr() string {
	if x != nil {
		return x.ClientListenAddr
	}
	return ""
}

// 玩家登录游戏服
type PlayerEntryGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	LoginSession  string                 `protobuf:"bytes,2,opt,name=LoginSession,proto3" json:"LoginSession,omitempty"` // 账号验证成功后的缓存session
	RegionId      int32                  `protobuf:"varint,3,opt,name=RegionId,proto3" json:"RegionId,omitempty"`        // 区服id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEntryGameReq) Reset() {
	*x = PlayerEntryGameReq{}
	mi := &file_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEntryGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEntryGameReq) ProtoMessage() {}

func (x *PlayerEntryGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEntryGameReq.ProtoReflect.Descriptor instead.
func (*PlayerEntryGameReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerEntryGameReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerEntryGameReq) GetLoginSession() string {
	if x != nil {
		return x.LoginSession
	}
	return ""
}

func (x *PlayerEntryGameReq) GetRegionId() int32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

// 玩家登录游戏服回复
type PlayerEntryGameRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	RegionId      int32                  `protobuf:"varint,3,opt,name=RegionId,proto3" json:"RegionId,omitempty"` // 区服id
	PlayerName    string                 `protobuf:"bytes,4,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"`
	GameServerId  int32                  `protobuf:"varint,5,opt,name=GameServerId,proto3" json:"GameServerId,omitempty"` // game服Id,客户端重连时需要带上
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEntryGameRes) Reset() {
	*x = PlayerEntryGameRes{}
	mi := &file_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEntryGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEntryGameRes) ProtoMessage() {}

func (x *PlayerEntryGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEntryGameRes.ProtoReflect.Descriptor instead.
func (*PlayerEntryGameRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerEntryGameRes) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerEntryGameRes) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerEntryGameRes) GetRegionId() int32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *PlayerEntryGameRes) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerEntryGameRes) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

// 玩家重连游戏服
type PlayerReconnectGameReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	PlayerId         int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	ReconnectSession string                 `protobuf:"bytes,3,opt,name=ReconnectSession,proto3" json:"ReconnectSession,omitempty"` // 重连验证session
	Version          string                 `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`                   // 客户端版本号,如0.0.0.1
	GameServerId     int32                  `protobuf:"varint,5,opt,name=GameServerId,proto3" json:"GameServerId,omitempty"`        // game服Id
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerReconnectGameReq) Reset() {
	*x = PlayerReconnectGameReq{}
	mi := &file_login_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReconnectGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReconnectGameReq) ProtoMessage() {}

func (x *PlayerReconnectGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReconnectGameReq.ProtoReflect.Descriptor instead.
func (*PlayerReconnectGameReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerReconnectGameReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerReconnectGameReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerReconnectGameReq) GetReconnectSession() string {
	if x != nil {
		return x.ReconnectSession
	}
	return ""
}

func (x *PlayerReconnectGameReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PlayerReconnectGameReq) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

// 玩家重连游戏服
type PlayerReconnectGameRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	GameServerId  int32                  `protobuf:"varint,3,opt,name=GameServerId,proto3" json:"GameServerId,omitempty"` // game服Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReconnectGameRes) Reset() {
	*x = PlayerReconnectGameRes{}
	mi := &file_login_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReconnectGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReconnectGameRes) ProtoMessage() {}

func (x *PlayerReconnectGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReconnectGameRes.ProtoReflect.Descriptor instead.
func (*PlayerReconnectGameRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerReconnectGameRes) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerReconnectGameRes) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerReconnectGameRes) GetGameServerId() int32 {
	if x != nil {
		return x.GameServerId
	}
	return 0
}

// 创建角色
type CreatePlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	LoginSession  string                 `protobuf:"bytes,2,opt,name=LoginSession,proto3" json:"LoginSession,omitempty"` // 账号验证成功后的缓存session
	RegionId      int32                  `protobuf:"varint,3,opt,name=RegionId,proto3" json:"RegionId,omitempty"`        // 区服id
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`                 // 玩家名
	Gender        int32                  `protobuf:"varint,5,opt,name=Gender,proto3" json:"Gender,omitempty"`            // 性别
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerReq) Reset() {
	*x = CreatePlayerReq{}
	mi := &file_login_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerReq) ProtoMessage() {}

func (x *CreatePlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerReq.ProtoReflect.Descriptor instead.
func (*CreatePlayerReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePlayerReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreatePlayerReq) GetLoginSession() string {
	if x != nil {
		return x.LoginSession
	}
	return ""
}

func (x *CreatePlayerReq) GetRegionId() int32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *CreatePlayerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlayerReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

// 创建角色
type CreatePlayerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	RegionId      int32                  `protobuf:"varint,2,opt,name=RegionId,proto3" json:"RegionId,omitempty"` // 区服id
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`          // 玩家名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRes) Reset() {
	*x = CreatePlayerRes{}
	mi := &file_login_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRes) ProtoMessage() {}

func (x *CreatePlayerRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRes.ProtoReflect.Descriptor instead.
func (*CreatePlayerRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePlayerRes) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreatePlayerRes) GetRegionId() int32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *CreatePlayerRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 测试命令
type TestCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCmd) Reset() {
	*x = TestCmd{}
	mi := &file_login_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCmd) ProtoMessage() {}

func (x *TestCmd) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCmd.ProtoReflect.Descriptor instead.
func (*TestCmd) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{11}
}

func (x *TestCmd) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

// 测试命令响应
type TestRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRes) Reset() {
	*x = TestRes{}
	mi := &file_login_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRes) ProtoMessage() {}

func (x *TestRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRes.ProtoReflect.Descriptor instead.
func (*TestRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{12}
}

func (x *TestRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_login_proto protoreflect.FileDescriptor

const file_login_proto_rawDesc = "" +
	"\n" +
	"\vlogin.proto\x12\agserver\x1a\fplayer.proto\"b\n" +
	"\bLoginReq\x12 \n" +
	"\vAccountName\x18\x01 \x01(\tR\vAccountName\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12\x18\n" +
	"\aVersion\x18\x03 \x01(\tR\aVersion\"\xa7\x01\n" +
	"\bLoginRes\x12 \n" +
	"\vAccountName\x18\x01 \x01(\tR\vAccountName\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\x03R\tAccountId\x12\"\n" +
	"\fLoginSession\x18\x03 \x01(\tR\fLoginSession\x127\n" +
	"\n" +
	"GameServer\x18\x04 \x01(\v2\x17.gserver.GameServerInfoR\n" +
	"GameServer\"J\n" +
	"\n" +
	"AccountReg\x12 \n" +
	"\vAccountName\x18\x01 \x01(\tR\vAccountName\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"L\n" +
	"\n" +
	"AccountRes\x12 \n" +
	"\vAccountName\x18\x01 \x01(\tR\vAccountName\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\x03R\tAccountId\"X\n" +
	"\x0eGameServerInfo\x12\x1a\n" +
	"\bServerId\x18\x01 \x01(\x05R\bServerId\x12*\n" +
	"\x10ClientListenAddr\x18\x02 \x01(\tR\x10ClientListenAddr\"r\n" +
	"\x12PlayerEntryGameReq\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\x03R\tAccountId\x12\"\n" +
	"\fLoginSession\x18\x02 \x01(\tR\fLoginSession\x12\x1a\n" +
	"\bRegionId\x18\x03 \x01(\x05R\bRegionId\"\xae\x01\n" +
	"\x12PlayerEntryGameRes\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\x03R\tAccountId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\x12\x1a\n" +
	"\bRegionId\x18\x03 \x01(\x05R\bRegionId\x12\x1e\n" +
	"\n" +
	"PlayerName\x18\x04 \x01(\tR\n" +
	"PlayerName\x12\"\n" +
	"\fGameServerId\x18\x05 \x01(\x05R\fGameServerId\"\xbc\x01\n" +
	"\x16PlayerReconnectGameReq\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\x03R\tAccountId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\x12*\n" +
	"\x10ReconnectSession\x18\x03 \x01(\tR\x10ReconnectSession\x12\x18\n" +
	"\aVersion\x18\x04 \x01(\tR\aVersion\x12\"\n" +
	"\fGameServerId\x18\x05 \x01(\x05R\fGameServerId\"v\n" +
	"\x16PlayerReconnectGameRes\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\x03R\tAccountId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\x12\"\n" +
	"\fGameServerId\x18\x03 \x01(\x05R\fGameServerId\"\x9b\x01\n" +
	"\x0fCreatePlayerReq\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\x03R\tAccountId\x12\"\n" +
	"\fLoginSession\x18\x02 \x01(\tR\fLoginSession\x12\x1a\n" +
	"\bRegionId\x18\x03 \x01(\x05R\bRegionId\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Gender\x18\x05 \x01(\x05R\x06Gender\"_\n" +
	"\x0fCreatePlayerRes\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\x03R\tAccountId\x12\x1a\n" +
	"\bRegionId\x18\x02 \x01(\x05R\bRegionId\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\"\x1b\n" +
	"\aTestCmd\x12\x10\n" +
	"\x03Cmd\x18\x01 \x01(\tR\x03Cmd\"!\n" +
	"\aTestRes\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\tR\x06ResultB\x06Z\x04./pbb\x06proto3"

var (
	file_login_proto_rawDescOnce sync.Once
	file_login_proto_rawDescData []byte
)

func file_login_proto_rawDescGZIP() []byte {
	file_login_proto_rawDescOnce.Do(func() {
		file_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)))
	})
	return file_login_proto_rawDescData
}

var file_login_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_login_proto_goTypes = []any{
	(*LoginReq)(nil),               // 0: gserver.LoginReq
	(*LoginRes)(nil),               // 1: gserver.LoginRes
	(*AccountReg)(nil),             // 2: gserver.AccountReg
	(*AccountRes)(nil),             // 3: gserver.AccountRes
	(*GameServerInfo)(nil),         // 4: gserver.GameServerInfo
	(*PlayerEntryGameReq)(nil),     // 5: gserver.PlayerEntryGameReq
	(*PlayerEntryGameRes)(nil),     // 6: gserver.PlayerEntryGameRes
	(*PlayerReconnectGameReq)(nil), // 7: gserver.PlayerReconnectGameReq
	(*PlayerReconnectGameRes)(nil), // 8: gserver.PlayerReconnectGameRes
	(*CreatePlayerReq)(nil),        // 9: gserver.CreatePlayerReq
	(*CreatePlayerRes)(nil),        // 10: gserver.CreatePlayerRes
	(*TestCmd)(nil),                // 11: gserver.TestCmd
	(*TestRes)(nil),                // 12: gserver.TestRes
}
var file_login_proto_depIdxs = []int32{
	4, // 0: gserver.LoginRes.GameServer:type_name -> gserver.GameServerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_login_proto_init() }
func file_login_proto_init() {
	if File_login_proto != nil {
		return
	}
	file_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_proto_goTypes,
		DependencyIndexes: file_login_proto_depIdxs,
		MessageInfos:      file_login_proto_msgTypes,
	}.Build()
	File_login_proto = out.File
	file_login_proto_goTypes = nil
	file_login_proto_depIdxs = nil
}
