// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: player.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家基础信息
type BaseInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Gender              int32                  `protobuf:"varint,1,opt,name=gender,proto3" json:"gender,omitempty"`                           // 性别
	Level               int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`                             // 等级
	Exp                 int32                  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`                                 // 经验值
	TotalPay            int32                  `protobuf:"varint,4,opt,name=totalPay,proto3" json:"totalPay,omitempty"`                       // 累充总额
	LastUpdateDate      int32                  `protobuf:"varint,5,opt,name=lastUpdateDate,proto3" json:"lastUpdateDate,omitempty"`           // 上次刷新日期,格式:yyyymmdd
	LastLoginTimestamp  int64                  `protobuf:"varint,6,opt,name=lastLoginTimestamp,proto3" json:"lastLoginTimestamp,omitempty"`   // 最近一次登录时间戳
	LastLogoutTimestamp int64                  `protobuf:"varint,7,opt,name=lastLogoutTimestamp,proto3" json:"lastLogoutTimestamp,omitempty"` // 最近一次退出时间戳
	TotalOnlineSeconds  int32                  `protobuf:"varint,8,opt,name=totalOnlineSeconds,proto3" json:"totalOnlineSeconds,omitempty"`   // 总在线时长(秒)
	ReconnectSession    string                 `protobuf:"bytes,9,opt,name=ReconnectSession,proto3" json:"ReconnectSession,omitempty"`        // 重连验证session
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *BaseInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *BaseInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BaseInfo) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *BaseInfo) GetTotalPay() int32 {
	if x != nil {
		return x.TotalPay
	}
	return 0
}

func (x *BaseInfo) GetLastUpdateDate() int32 {
	if x != nil {
		return x.LastUpdateDate
	}
	return 0
}

func (x *BaseInfo) GetLastLoginTimestamp() int64 {
	if x != nil {
		return x.LastLoginTimestamp
	}
	return 0
}

func (x *BaseInfo) GetLastLogoutTimestamp() int64 {
	if x != nil {
		return x.LastLogoutTimestamp
	}
	return 0
}

func (x *BaseInfo) GetTotalOnlineSeconds() int32 {
	if x != nil {
		return x.TotalOnlineSeconds
	}
	return 0
}

func (x *BaseInfo) GetReconnectSession() string {
	if x != nil {
		return x.ReconnectSession
	}
	return ""
}

// 背包模块数据
type BagSaveData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountItem     map[int32]int32        `protobuf:"bytes,1,rep,name=CountItem,proto3" json:"CountItem,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	UniqueItem    map[int64][]byte       `protobuf:"bytes,2,rep,name=UniqueItem,proto3" json:"UniqueItem,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Equip         map[int64][]byte       `protobuf:"bytes,3,rep,name=Equip,proto3" json:"Equip,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagSaveData) Reset() {
	*x = BagSaveData{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagSaveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagSaveData) ProtoMessage() {}

func (x *BagSaveData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagSaveData.ProtoReflect.Descriptor instead.
func (*BagSaveData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *BagSaveData) GetCountItem() map[int32]int32 {
	if x != nil {
		return x.CountItem
	}
	return nil
}

func (x *BagSaveData) GetUniqueItem() map[int64][]byte {
	if x != nil {
		return x.UniqueItem
	}
	return nil
}

func (x *BagSaveData) GetEquip() map[int64][]byte {
	if x != nil {
		return x.Equip
	}
	return nil
}

// 任务模块数据
type QuestSaveData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finished      map[int32][]byte       `protobuf:"bytes,1,rep,name=finished,proto3" json:"finished,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 已完成的任务
	Quests        map[int32][]byte       `protobuf:"bytes,2,rep,name=quests,proto3" json:"quests,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // 进行中的任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestSaveData) Reset() {
	*x = QuestSaveData{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestSaveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestSaveData) ProtoMessage() {}

func (x *QuestSaveData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestSaveData.ProtoReflect.Descriptor instead.
func (*QuestSaveData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *QuestSaveData) GetFinished() map[int32][]byte {
	if x != nil {
		return x.Finished
	}
	return nil
}

func (x *QuestSaveData) GetQuests() map[int32][]byte {
	if x != nil {
		return x.Quests
	}
	return nil
}

// 任务数据
type QuestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=cfgId,proto3" json:"cfgId,omitempty"`           // 配置id
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`     // 进度
	ActivityId    int32                  `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动id,只有活动子任务才会有值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestData) Reset() {
	*x = QuestData{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestData) ProtoMessage() {}

func (x *QuestData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestData.ProtoReflect.Descriptor instead.
func (*QuestData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *QuestData) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *QuestData) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *QuestData) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

// 已完成的任务
type FinishedQuestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int32                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 完成时间戳(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishedQuestData) Reset() {
	*x = FinishedQuestData{}
	mi := &file_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishedQuestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishedQuestData) ProtoMessage() {}

func (x *FinishedQuestData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishedQuestData.ProtoReflect.Descriptor instead.
func (*FinishedQuestData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{4}
}

func (x *FinishedQuestData) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 玩家身上的公会数据
type PlayerGuildData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       int64                  `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId,omitempty"` // 公会id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGuildData) Reset() {
	*x = PlayerGuildData{}
	mi := &file_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGuildData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGuildData) ProtoMessage() {}

func (x *PlayerGuildData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGuildData.ProtoReflect.Descriptor instead.
func (*PlayerGuildData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerGuildData) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

// 玩家在mongo中的保存格式
// 用于一次性把玩家数据加载进来
type PlayerData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	XId             int64                  `protobuf:"varint,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`     // 玩家id
	Name            string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`            // 玩家名
	AccountId       int64                  `protobuf:"varint,3,opt,name=AccountId,proto3" json:"AccountId,omitempty"` // 账号id
	RegionId        int32                  `protobuf:"varint,4,opt,name=RegionId,proto3" json:"RegionId,omitempty"`   // 区服id
	BaseInfo        *BaseInfo              `protobuf:"bytes,5,opt,name=BaseInfo,proto3" json:"BaseInfo,omitempty"`
	Bags            *BagSaveData           `protobuf:"bytes,7,opt,name=Bags,proto3" json:"Bags,omitempty"`
	Quest           *QuestSaveData         `protobuf:"bytes,8,opt,name=Quest,proto3" json:"Quest,omitempty"`
	Guild           *PlayerGuildData       `protobuf:"bytes,9,opt,name=Guild,proto3" json:"Guild,omitempty"`
	PendingMessages map[int64][]byte       `protobuf:"bytes,10,rep,name=PendingMessages,proto3" json:"PendingMessages,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map<int64,*PendingMessage>
	Activities      map[int32][]byte       `protobuf:"bytes,11,rep,name=Activities,proto3" json:"Activities,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`           // map<int32,*ActivityDefaultBaseData>
	Exchange        map[int32][]byte       `protobuf:"bytes,12,rep,name=Exchange,proto3" json:"Exchange,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`               // map<int32,*ExchangeRecord>
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerData) Reset() {
	*x = PlayerData{}
	mi := &file_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerData) ProtoMessage() {}

func (x *PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerData.ProtoReflect.Descriptor instead.
func (*PlayerData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerData) GetXId() int64 {
	if x != nil {
		return x.XId
	}
	return 0
}

func (x *PlayerData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerData) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerData) GetRegionId() int32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *PlayerData) GetBaseInfo() *BaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

func (x *PlayerData) GetBags() *BagSaveData {
	if x != nil {
		return x.Bags
	}
	return nil
}

func (x *PlayerData) GetQuest() *QuestSaveData {
	if x != nil {
		return x.Quest
	}
	return nil
}

func (x *PlayerData) GetGuild() *PlayerGuildData {
	if x != nil {
		return x.Guild
	}
	return nil
}

func (x *PlayerData) GetPendingMessages() map[int64][]byte {
	if x != nil {
		return x.PendingMessages
	}
	return nil
}

func (x *PlayerData) GetActivities() map[int32][]byte {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *PlayerData) GetExchange() map[int32][]byte {
	if x != nil {
		return x.Exchange
	}
	return nil
}

// 默认活动模板的基础数据
type ActivityDefaultBaseData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LastUpdateTime  int32                  `protobuf:"varint,1,opt,name=LastUpdateTime,proto3" json:"LastUpdateTime,omitempty"`                                                                             // 刷新时间戳
	JoinTime        int32                  `protobuf:"varint,4,opt,name=JoinTime,proto3" json:"JoinTime,omitempty"`                                                                                         // 参加活动的时间(时间戳)
	PropertiesInt32 map[string]int32       `protobuf:"bytes,5,rep,name=PropertiesInt32,proto3" json:"PropertiesInt32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 动态属性(int32)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivityDefaultBaseData) Reset() {
	*x = ActivityDefaultBaseData{}
	mi := &file_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityDefaultBaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityDefaultBaseData) ProtoMessage() {}

func (x *ActivityDefaultBaseData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityDefaultBaseData.ProtoReflect.Descriptor instead.
func (*ActivityDefaultBaseData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{7}
}

func (x *ActivityDefaultBaseData) GetLastUpdateTime() int32 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

func (x *ActivityDefaultBaseData) GetJoinTime() int32 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

func (x *ActivityDefaultBaseData) GetPropertiesInt32() map[string]int32 {
	if x != nil {
		return x.PropertiesInt32
	}
	return nil
}

// 待处理消息
type PendingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`         // 唯一id
	PacketCommand int32                  `protobuf:"varint,2,opt,name=packetCommand,proto3" json:"packetCommand,omitempty"` // 消息号
	PacketData    *anypb.Any             `protobuf:"bytes,3,opt,name=packetData,proto3" json:"packetData,omitempty"`        // 消息内容
	Timestamp     int32                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingMessage) Reset() {
	*x = PendingMessage{}
	mi := &file_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMessage) ProtoMessage() {}

func (x *PendingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMessage.ProtoReflect.Descriptor instead.
func (*PendingMessage) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{8}
}

func (x *PendingMessage) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PendingMessage) GetPacketCommand() int32 {
	if x != nil {
		return x.PacketCommand
	}
	return 0
}

func (x *PendingMessage) GetPacketData() *anypb.Any {
	if x != nil {
		return x.PacketData
	}
	return nil
}

func (x *PendingMessage) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 兑换记录
type ExchangeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Timestamp     int32                  `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"` // 最近一次兑换的时间戳(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRecord) Reset() {
	*x = ExchangeRecord{}
	mi := &file_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRecord) ProtoMessage() {}

func (x *ExchangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRecord.ProtoReflect.Descriptor instead.
func (*ExchangeRecord) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{9}
}

func (x *ExchangeRecord) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ExchangeRecord) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ExchangeRecord) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\agserver\x1a\x19google/protobuf/any.proto\"\xcc\x02\n" +
	"\bBaseInfo\x12\x16\n" +
	"\x06gender\x18\x01 \x01(\x05R\x06gender\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x05R\x03exp\x12\x1a\n" +
	"\btotalPay\x18\x04 \x01(\x05R\btotalPay\x12&\n" +
	"\x0elastUpdateDate\x18\x05 \x01(\x05R\x0elastUpdateDate\x12.\n" +
	"\x12lastLoginTimestamp\x18\x06 \x01(\x03R\x12lastLoginTimestamp\x120\n" +
	"\x13lastLogoutTimestamp\x18\a \x01(\x03R\x13lastLogoutTimestamp\x12.\n" +
	"\x12totalOnlineSeconds\x18\b \x01(\x05R\x12totalOnlineSeconds\x12*\n" +
	"\x10ReconnectSession\x18\t \x01(\tR\x10ReconnectSession\"\x84\x03\n" +
	"\vBagSaveData\x12A\n" +
	"\tCountItem\x18\x01 \x03(\v2#.gserver.BagSaveData.CountItemEntryR\tCountItem\x12D\n" +
	"\n" +
	"UniqueItem\x18\x02 \x03(\v2$.gserver.BagSaveData.UniqueItemEntryR\n" +
	"UniqueItem\x125\n" +
	"\x05Equip\x18\x03 \x03(\v2\x1f.gserver.BagSaveData.EquipEntryR\x05Equip\x1a<\n" +
	"\x0eCountItemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fUniqueItemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"EquipEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x85\x02\n" +
	"\rQuestSaveData\x12@\n" +
	"\bfinished\x18\x01 \x03(\v2$.gserver.QuestSaveData.FinishedEntryR\bfinished\x12:\n" +
	"\x06quests\x18\x02 \x03(\v2\".gserver.QuestSaveData.QuestsEntryR\x06quests\x1a;\n" +
	"\rFinishedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a9\n" +
	"\vQuestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"]\n" +
	"\tQuestData\x12\x14\n" +
	"\x05cfgId\x18\x01 \x01(\x05R\x05cfgId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x1e\n" +
	"\n" +
	"activityId\x18\x03 \x01(\x05R\n" +
	"activityId\"1\n" +
	"\x11FinishedQuestData\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x05R\ttimestamp\"+\n" +
	"\x0fPlayerGuildData\x12\x18\n" +
	"\aguildId\x18\x01 \x01(\x03R\aguildId\"\xba\x05\n" +
	"\n" +
	"PlayerData\x12\x0f\n" +
	"\x03_id\x18\x01 \x01(\x03R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\tAccountId\x18\x03 \x01(\x03R\tAccountId\x12\x1a\n" +
	"\bRegionId\x18\x04 \x01(\x05R\bRegionId\x12-\n" +
	"\bBaseInfo\x18\x05 \x01(\v2\x11.gserver.BaseInfoR\bBaseInfo\x12(\n" +
	"\x04Bags\x18\a \x01(\v2\x14.gserver.BagSaveDataR\x04Bags\x12,\n" +
	"\x05Quest\x18\b \x01(\v2\x16.gserver.QuestSaveDataR\x05Quest\x12.\n" +
	"\x05Guild\x18\t \x01(\v2\x18.gserver.PlayerGuildDataR\x05Guild\x12R\n" +
	"\x0fPendingMessages\x18\n" +
	" \x03(\v2(.gserver.PlayerData.PendingMessagesEntryR\x0fPendingMessages\x12C\n" +
	"\n" +
	"Activities\x18\v \x03(\v2#.gserver.PlayerData.ActivitiesEntryR\n" +
	"Activities\x12=\n" +
	"\bExchange\x18\f \x03(\v2!.gserver.PlayerData.ExchangeEntryR\bExchange\x1aB\n" +
	"\x14PendingMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a=\n" +
	"\x0fActivitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rExchangeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x82\x02\n" +
	"\x17ActivityDefaultBaseData\x12&\n" +
	"\x0eLastUpdateTime\x18\x01 \x01(\x05R\x0eLastUpdateTime\x12\x1a\n" +
	"\bJoinTime\x18\x04 \x01(\x05R\bJoinTime\x12_\n" +
	"\x0fPropertiesInt32\x18\x05 \x03(\v25.gserver.ActivityDefaultBaseData.PropertiesInt32EntryR\x0fPropertiesInt32\x1aB\n" +
	"\x14PropertiesInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xa8\x01\n" +
	"\x0ePendingMessage\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\x03R\tmessageId\x12$\n" +
	"\rpacketCommand\x18\x02 \x01(\x05R\rpacketCommand\x124\n" +
	"\n" +
	"packetData\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"packetData\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x05R\ttimestamp\"Z\n" +
	"\x0eExchangeRecord\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\x05R\x05CfgId\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x05R\x05Count\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\x05R\tTimestampB\x06Z\x04./pbb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_player_proto_goTypes = []any{
	(*BaseInfo)(nil),                // 0: gserver.BaseInfo
	(*BagSaveData)(nil),             // 1: gserver.BagSaveData
	(*QuestSaveData)(nil),           // 2: gserver.QuestSaveData
	(*QuestData)(nil),               // 3: gserver.QuestData
	(*FinishedQuestData)(nil),       // 4: gserver.FinishedQuestData
	(*PlayerGuildData)(nil),         // 5: gserver.PlayerGuildData
	(*PlayerData)(nil),              // 6: gserver.PlayerData
	(*ActivityDefaultBaseData)(nil), // 7: gserver.ActivityDefaultBaseData
	(*PendingMessage)(nil),          // 8: gserver.PendingMessage
	(*ExchangeRecord)(nil),          // 9: gserver.ExchangeRecord
	nil,                             // 10: gserver.BagSaveData.CountItemEntry
	nil,                             // 11: gserver.BagSaveData.UniqueItemEntry
	nil,                             // 12: gserver.BagSaveData.EquipEntry
	nil,                             // 13: gserver.QuestSaveData.FinishedEntry
	nil,                             // 14: gserver.QuestSaveData.QuestsEntry
	nil,                             // 15: gserver.PlayerData.PendingMessagesEntry
	nil,                             // 16: gserver.PlayerData.ActivitiesEntry
	nil,                             // 17: gserver.PlayerData.ExchangeEntry
	nil,                             // 18: gserver.ActivityDefaultBaseData.PropertiesInt32Entry
	(*anypb.Any)(nil),               // 19: google.protobuf.Any
}
var file_player_proto_depIdxs = []int32{
	10, // 0: gserver.BagSaveData.CountItem:type_name -> gserver.BagSaveData.CountItemEntry
	11, // 1: gserver.BagSaveData.UniqueItem:type_name -> gserver.BagSaveData.UniqueItemEntry
	12, // 2: gserver.BagSaveData.Equip:type_name -> gserver.BagSaveData.EquipEntry
	13, // 3: gserver.QuestSaveData.finished:type_name -> gserver.QuestSaveData.FinishedEntry
	14, // 4: gserver.QuestSaveData.quests:type_name -> gserver.QuestSaveData.QuestsEntry
	0,  // 5: gserver.PlayerData.BaseInfo:type_name -> gserver.BaseInfo
	1,  // 6: gserver.PlayerData.Bags:type_name -> gserver.BagSaveData
	2,  // 7: gserver.PlayerData.Quest:type_name -> gserver.QuestSaveData
	5,  // 8: gserver.PlayerData.Guild:type_name -> gserver.PlayerGuildData
	15, // 9: gserver.PlayerData.PendingMessages:type_name -> gserver.PlayerData.PendingMessagesEntry
	16, // 10: gserver.PlayerData.Activities:type_name -> gserver.PlayerData.ActivitiesEntry
	17, // 11: gserver.PlayerData.Exchange:type_name -> gserver.PlayerData.ExchangeEntry
	18, // 12: gserver.ActivityDefaultBaseData.PropertiesInt32:type_name -> gserver.ActivityDefaultBaseData.PropertiesInt32Entry
	19, // 13: gserver.PendingMessage.packetData:type_name -> google.protobuf.Any
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
