// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: route.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 路由选项(位掩码,可组合使用)
type RouteOption int32

const (
	RouteOption_RouteOption_None             RouteOption = 0
	RouteOption_RouteOption_DirectSendClient RouteOption = 1 // 直接转发给客户端,不做逻辑处理
	RouteOption_RouteOption_SaveDb           RouteOption = 2 // 先存数据库,防止路由失败造成消息丢失
)

// Enum value maps for RouteOption.
var (
	RouteOption_name = map[int32]string{
		0: "RouteOption_None",
		1: "RouteOption_DirectSendClient",
		2: "RouteOption_SaveDb",
	}
	RouteOption_value = map[string]int32{
		"RouteOption_None":             0,
		"RouteOption_DirectSendClient": 1,
		"RouteOption_SaveDb":           2,
	}
)

func (x RouteOption) Enum() *RouteOption {
	p := new(RouteOption)
	*p = x
	return p
}

func (x RouteOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteOption) Descriptor() protoreflect.EnumDescriptor {
	return file_route_proto_enumTypes[0].Descriptor()
}

func (RouteOption) Type() protoreflect.EnumType {
	return &file_route_proto_enumTypes[0]
}

func (x RouteOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteOption.Descriptor instead.
func (RouteOption) EnumDescriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{0}
}

// [其他服或其他协程]发给[game服]再路由转发给玩家的消息
// otherserver -> game -> player
type RoutePlayerMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Error            string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`                        // 错误码
	ToPlayerId       int64                  `protobuf:"varint,2,opt,name=ToPlayerId,proto3" json:"ToPlayerId,omitempty"`             // 玩家id
	PacketCommand    int32                  `protobuf:"varint,3,opt,name=PacketCommand,proto3" json:"PacketCommand,omitempty"`       // 消息号
	Options          int32                  `protobuf:"varint,4,opt,name=Options,proto3" json:"Options,omitempty"`                   // RouteOption位掩码
	PendingMessageId int64                  `protobuf:"varint,5,opt,name=PendingMessageId,proto3" json:"PendingMessageId,omitempty"` // 待处理消息id
	PacketData       *anypb.Any             `protobuf:"bytes,6,opt,name=PacketData,proto3" json:"PacketData,omitempty"`              // 转发的消息
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoutePlayerMessage) Reset() {
	*x = RoutePlayerMessage{}
	mi := &file_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePlayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePlayerMessage) ProtoMessage() {}

func (x *RoutePlayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePlayerMessage.ProtoReflect.Descriptor instead.
func (*RoutePlayerMessage) Descriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{0}
}

func (x *RoutePlayerMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RoutePlayerMessage) GetToPlayerId() int64 {
	if x != nil {
		return x.ToPlayerId
	}
	return 0
}

func (x *RoutePlayerMessage) GetPacketCommand() int32 {
	if x != nil {
		return x.PacketCommand
	}
	return 0
}

func (x *RoutePlayerMessage) GetOptions() int32 {
	if x != nil {
		return x.Options
	}
	return 0
}

func (x *RoutePlayerMessage) GetPendingMessageId() int64 {
	if x != nil {
		return x.PendingMessageId
	}
	return 0
}

func (x *RoutePlayerMessage) GetPacketData() *anypb.Any {
	if x != nil {
		return x.PacketData
	}
	return nil
}

// [game服]发给[其他服或其他协程]再路由到玩家所在的公会请求消息
// game -> otherserver -> guild
type GuildRoutePlayerMessageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromPlayerId   int64                  `protobuf:"varint,1,opt,name=FromPlayerId,proto3" json:"FromPlayerId,omitempty"`    // 玩家id
	FromGuildId    int64                  `protobuf:"varint,2,opt,name=FromGuildId,proto3" json:"FromGuildId,omitempty"`      // 玩家公会id
	FromServerId   int32                  `protobuf:"varint,3,opt,name=FromServerId,proto3" json:"FromServerId,omitempty"`    // 玩家当前所在服务器id
	FromPlayerName string                 `protobuf:"bytes,4,opt,name=FromPlayerName,proto3" json:"FromPlayerName,omitempty"` // 玩家名
	PacketCommand  int32                  `protobuf:"varint,5,opt,name=PacketCommand,proto3" json:"PacketCommand,omitempty"`  // 消息号
	PacketData     *anypb.Any             `protobuf:"bytes,6,opt,name=PacketData,proto3" json:"PacketData,omitempty"`         // 消息内容
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GuildRoutePlayerMessageReq) Reset() {
	*x = GuildRoutePlayerMessageReq{}
	mi := &file_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildRoutePlayerMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRoutePlayerMessageReq) ProtoMessage() {}

func (x *GuildRoutePlayerMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRoutePlayerMessageReq.ProtoReflect.Descriptor instead.
func (*GuildRoutePlayerMessageReq) Descriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{1}
}

func (x *GuildRoutePlayerMessageReq) GetFromPlayerId() int64 {
	if x != nil {
		return x.FromPlayerId
	}
	return 0
}

func (x *GuildRoutePlayerMessageReq) GetFromGuildId() int64 {
	if x != nil {
		return x.FromGuildId
	}
	return 0
}

func (x *GuildRoutePlayerMessageReq) GetFromServerId() int32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *GuildRoutePlayerMessageReq) GetFromPlayerName() string {
	if x != nil {
		return x.FromPlayerName
	}
	return ""
}

func (x *GuildRoutePlayerMessageReq) GetPacketCommand() int32 {
	if x != nil {
		return x.PacketCommand
	}
	return 0
}

func (x *GuildRoutePlayerMessageReq) GetPacketData() *anypb.Any {
	if x != nil {
		return x.PacketData
	}
	return nil
}

// [game服]发给[其他服]的玩家请求消息
// game -> otherserver(如fight)
type RoutePlayerMessageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromPlayerId   int64                  `protobuf:"varint,1,opt,name=FromPlayerId,proto3" json:"FromPlayerId,omitempty"`     // 玩家id
	FromGuildId    int64                  `protobuf:"varint,2,opt,name=FromGuildId,proto3" json:"FromGuildId,omitempty"`       // 玩家公会id
	FromServerId   int32                  `protobuf:"varint,3,opt,name=FromServerId,proto3" json:"FromServerId,omitempty"`     // 玩家当前所在服务器id
	FromPlayerName string                 `protobuf:"bytes,4,opt,name=FromPlayerName,proto3" json:"FromPlayerName,omitempty"`  // 玩家名
	PacketCommand  int32                  `protobuf:"varint,5,opt,name=PacketCommand,proto3" json:"PacketCommand,omitempty"`   // 消息号
	PacketData     *anypb.Any             `protobuf:"bytes,6,opt,name=PacketData,proto3" json:"PacketData,omitempty"`          // 消息内容
	TargetEntityId int64                  `protobuf:"varint,7,opt,name=TargetEntityId,proto3" json:"TargetEntityId,omitempty"` // 需要路由到的目标实体Id(如公会id,场景id等)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoutePlayerMessageReq) Reset() {
	*x = RoutePlayerMessageReq{}
	mi := &file_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePlayerMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePlayerMessageReq) ProtoMessage() {}

func (x *RoutePlayerMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePlayerMessageReq.ProtoReflect.Descriptor instead.
func (*RoutePlayerMessageReq) Descriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{2}
}

func (x *RoutePlayerMessageReq) GetFromPlayerId() int64 {
	if x != nil {
		return x.FromPlayerId
	}
	return 0
}

func (x *RoutePlayerMessageReq) GetFromGuildId() int64 {
	if x != nil {
		return x.FromGuildId
	}
	return 0
}

func (x *RoutePlayerMessageReq) GetFromServerId() int32 {
	if x != nil {
		return x.FromServerId
	}
	return 0
}

func (x *RoutePlayerMessageReq) GetFromPlayerName() string {
	if x != nil {
		return x.FromPlayerName
	}
	return ""
}

func (x *RoutePlayerMessageReq) GetPacketCommand() int32 {
	if x != nil {
		return x.PacketCommand
	}
	return 0
}

func (x *RoutePlayerMessageReq) GetPacketData() *anypb.Any {
	if x != nil {
		return x.PacketData
	}
	return nil
}

func (x *RoutePlayerMessageReq) GetTargetEntityId() int64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

var File_route_proto protoreflect.FileDescriptor

const file_route_proto_rawDesc = "" +
	"\n" +
	"\vroute.proto\x12\agserver\x1a\x19google/protobuf/any.proto\"\xec\x01\n" +
	"\x12RoutePlayerMessage\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\x12\x1e\n" +
	"\n" +
	"ToPlayerId\x18\x02 \x01(\x03R\n" +
	"ToPlayerId\x12$\n" +
	"\rPacketCommand\x18\x03 \x01(\x05R\rPacketCommand\x12\x18\n" +
	"\aOptions\x18\x04 \x01(\x05R\aOptions\x12*\n" +
	"\x10PendingMessageId\x18\x05 \x01(\x03R\x10PendingMessageId\x124\n" +
	"\n" +
	"PacketData\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"PacketData\"\x8a\x02\n" +
	"\x1aGuildRoutePlayerMessageReq\x12\"\n" +
	"\fFromPlayerId\x18\x01 \x01(\x03R\fFromPlayerId\x12 \n" +
	"\vFromGuildId\x18\x02 \x01(\x03R\vFromGuildId\x12\"\n" +
	"\fFromServerId\x18\x03 \x01(\x05R\fFromServerId\x12&\n" +
	"\x0eFromPlayerName\x18\x04 \x01(\tR\x0eFromPlayerName\x12$\n" +
	"\rPacketCommand\x18\x05 \x01(\x05R\rPacketCommand\x124\n" +
	"\n" +
	"PacketData\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"PacketData\"\xad\x02\n" +
	"\x15RoutePlayerMessageReq\x12\"\n" +
	"\fFromPlayerId\x18\x01 \x01(\x03R\fFromPlayerId\x12 \n" +
	"\vFromGuildId\x18\x02 \x01(\x03R\vFromGuildId\x12\"\n" +
	"\fFromServerId\x18\x03 \x01(\x05R\fFromServerId\x12&\n" +
	"\x0eFromPlayerName\x18\x04 \x01(\tR\x0eFromPlayerName\x12$\n" +
	"\rPacketCommand\x18\x05 \x01(\x05R\rPacketCommand\x124\n" +
	"\n" +
	"PacketData\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"PacketData\x12&\n" +
	"\x0eTargetEntityId\x18\a \x01(\x03R\x0eTargetEntityId*]\n" +
	"\vRouteOption\x12\x14\n" +
	"\x10RouteOption_None\x10\x00\x12 \n" +
	"\x1cRouteOption_DirectSendClient\x10\x01\x12\x16\n" +
	"\x12RouteOption_SaveDb\x10\x02B\x06Z\x04./pbb\x06proto3"

var (
	file_route_proto_rawDescOnce sync.Once
	file_route_proto_rawDescData []byte
)

func file_route_proto_rawDescGZIP() []byte {
	file_route_proto_rawDescOnce.Do(func() {
		file_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_route_proto_rawDesc), len(file_route_proto_rawDesc)))
	})
	return file_route_proto_rawDescData
}

var file_route_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_route_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_route_proto_goTypes = []any{
	(RouteOption)(0),                   // 0: gserver.RouteOption
	(*RoutePlayerMessage)(nil),         // 1: gserver.RoutePlayerMessage
	(*GuildRoutePlayerMessageReq)(nil), // 2: gserver.GuildRoutePlayerMessageReq
	(*RoutePlayerMessageReq)(nil),      // 3: gserver.RoutePlayerMessageReq
	(*anypb.Any)(nil),                  // 4: google.protobuf.Any
}
var file_route_proto_depIdxs = []int32{
	4, // 0: gserver.RoutePlayerMessage.PacketData:type_name -> google.protobuf.Any
	4, // 1: gserver.GuildRoutePlayerMessageReq.PacketData:type_name -> google.protobuf.Any
	4, // 2: gserver.RoutePlayerMessageReq.PacketData:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_route_proto_init() }
func file_route_proto_init() {
	if File_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_route_proto_rawDesc), len(file_route_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_route_proto_goTypes,
		DependencyIndexes: file_route_proto_depIdxs,
		EnumInfos:         file_route_proto_enumTypes,
		MessageInfos:      file_route_proto_msgTypes,
	}.Build()
	File_route_proto = out.File
	file_route_proto_goTypes = nil
	file_route_proto_depIdxs = nil
}
