// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: server_base.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器信息
type ServerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         int32                  `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`                // 服务器id
	ServerType       string                 `protobuf:"bytes,2,opt,name=serverType,proto3" json:"serverType,omitempty"`             // 服务器类型
	ServerListenAddr string                 `protobuf:"bytes,3,opt,name=serverListenAddr,proto3" json:"serverListenAddr,omitempty"` // 监听服务器地址
	ClientListenAddr string                 `protobuf:"bytes,4,opt,name=clientListenAddr,proto3" json:"clientListenAddr,omitempty"` // 监听客户端地址
	GateListenAddr   string                 `protobuf:"bytes,5,opt,name=gateListenAddr,proto3" json:"gateListenAddr,omitempty"`     // 监听网关地址
	LastActiveTime   int64                  `protobuf:"varint,6,opt,name=lastActiveTime,proto3" json:"lastActiveTime,omitempty"`    // 最近上传信息的时间戳(毫秒)
	Ping             int32                  `protobuf:"varint,7,opt,name=ping,proto3" json:"ping,omitempty"`                        // ping值(毫秒)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_server_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerInfo) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *ServerInfo) GetServerListenAddr() string {
	if x != nil {
		return x.ServerListenAddr
	}
	return ""
}

func (x *ServerInfo) GetClientListenAddr() string {
	if x != nil {
		return x.ClientListenAddr
	}
	return ""
}

func (x *ServerInfo) GetGateListenAddr() string {
	if x != nil {
		return x.GateListenAddr
	}
	return ""
}

func (x *ServerInfo) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

func (x *ServerInfo) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

// 踢玩家下线req
type KickPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"` // 账号id
	PlayerId      int64                  `protobuf:"varint,2,opt,name=playerId,proto3" json:"playerId,omitempty"`   // 玩家id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerReq) Reset() {
	*x = KickPlayerReq{}
	mi := &file_server_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerReq) ProtoMessage() {}

func (x *KickPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerReq.ProtoReflect.Descriptor instead.
func (*KickPlayerReq) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{1}
}

func (x *KickPlayerReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *KickPlayerReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 踢玩家下线res
type KickPlayerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"` // 账号id
	PlayerId      int64                  `protobuf:"varint,3,opt,name=playerId,proto3" json:"playerId,omitempty"`   // 玩家id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerRes) Reset() {
	*x = KickPlayerRes{}
	mi := &file_server_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRes) ProtoMessage() {}

func (x *KickPlayerRes) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRes.ProtoReflect.Descriptor instead.
func (*KickPlayerRes) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{2}
}

func (x *KickPlayerRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *KickPlayerRes) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *KickPlayerRes) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 客户端掉线
type ClientDisconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientConnId  uint32                 `protobuf:"varint,1,opt,name=clientConnId,proto3" json:"clientConnId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDisconnect) Reset() {
	*x = ClientDisconnect{}
	mi := &file_server_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnect) ProtoMessage() {}

func (x *ClientDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnect.ProtoReflect.Descriptor instead.
func (*ClientDisconnect) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{3}
}

func (x *ClientDisconnect) GetClientConnId() uint32 {
	if x != nil {
		return x.ClientConnId
	}
	return 0
}

// 服务器连接上其他服务器时,发的初始化信息
type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`    // 服务器id
	ServerType    string                 `protobuf:"bytes,2,opt,name=serverType,proto3" json:"serverType,omitempty"` // 服务器类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_server_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{4}
}

func (x *ServerHello) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerHello) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

var File_server_base_proto protoreflect.FileDescriptor

const file_server_base_proto_rawDesc = "" +
	"\n" +
	"\x11server_base.proto\x12\agserver\"\x84\x02\n" +
	"\n" +
	"ServerInfo\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\x05R\bserverId\x12\x1e\n" +
	"\n" +
	"serverType\x18\x02 \x01(\tR\n" +
	"serverType\x12*\n" +
	"\x10serverListenAddr\x18\x03 \x01(\tR\x10serverListenAddr\x12*\n" +
	"\x10clientListenAddr\x18\x04 \x01(\tR\x10clientListenAddr\x12&\n" +
	"\x0egateListenAddr\x18\x05 \x01(\tR\x0egateListenAddr\x12&\n" +
	"\x0elastActiveTime\x18\x06 \x01(\x03R\x0elastActiveTime\x12\x12\n" +
	"\x04ping\x18\a \x01(\x05R\x04ping\"I\n" +
	"\rKickPlayerReq\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\x03R\bplayerId\"_\n" +
	"\rKickPlayerRes\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1a\n" +
	"\bplayerId\x18\x03 \x01(\x03R\bplayerId\"6\n" +
	"\x10ClientDisconnect\x12\"\n" +
	"\fclientConnId\x18\x01 \x01(\rR\fclientConnId\"I\n" +
	"\vServerHello\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\x05R\bserverId\x12\x1e\n" +
	"\n" +
	"serverType\x18\x02 \x01(\tR\n" +
	"serverTypeB\x06Z\x04./pbb\x06proto3"

var (
	file_server_base_proto_rawDescOnce sync.Once
	file_server_base_proto_rawDescData []byte
)

func file_server_base_proto_rawDescGZIP() []byte {
	file_server_base_proto_rawDescOnce.Do(func() {
		file_server_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_base_proto_rawDesc), len(file_server_base_proto_rawDesc)))
	})
	return file_server_base_proto_rawDescData
}

var file_server_base_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_server_base_proto_goTypes = []any{
	(*ServerInfo)(nil),       // 0: gserver.ServerInfo
	(*KickPlayerReq)(nil),    // 1: gserver.KickPlayerReq
	(*KickPlayerRes)(nil),    // 2: gserver.KickPlayerRes
	(*ClientDisconnect)(nil), // 3: gserver.ClientDisconnect
	(*ServerHello)(nil),      // 4: gserver.ServerHello
}
var file_server_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_base_proto_init() }
func file_server_base_proto_init() {
	if File_server_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_base_proto_rawDesc), len(file_server_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_base_proto_goTypes,
		DependencyIndexes: file_server_base_proto_depIdxs,
		MessageInfos:      file_server_base_proto_msgTypes,
	}.Build()
	File_server_base_proto = out.File
	file_server_base_proto_goTypes = nil
	file_server_base_proto_depIdxs = nil
}
