// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: server_base.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器信息
type ServerInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerId           int32                  `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`                    // 服务器id
	ServerType         string                 `protobuf:"bytes,2,opt,name=ServerType,proto3" json:"ServerType,omitempty"`                 // 服务器类型
	ServerListenAddr   string                 `protobuf:"bytes,3,opt,name=ServerListenAddr,proto3" json:"ServerListenAddr,omitempty"`     // 监听服务器地址
	ClientListenAddr   string                 `protobuf:"bytes,4,opt,name=ClientListenAddr,proto3" json:"ClientListenAddr,omitempty"`     // 监听Tcp客户端地址
	WsClientListenAddr string                 `protobuf:"bytes,5,opt,name=WsClientListenAddr,proto3" json:"WsClientListenAddr,omitempty"` // 监听WebSocket客户端地址
	GateListenAddr     string                 `protobuf:"bytes,6,opt,name=GateListenAddr,proto3" json:"GateListenAddr,omitempty"`         // 监听网关地址
	LastActiveTime     int64                  `protobuf:"varint,7,opt,name=LastActiveTime,proto3" json:"LastActiveTime,omitempty"`        // 最近上传信息的时间戳(毫秒)
	Ping               int32                  `protobuf:"varint,8,opt,name=Ping,proto3" json:"Ping,omitempty"`                            // ping值(毫秒)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_server_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerInfo) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *ServerInfo) GetServerListenAddr() string {
	if x != nil {
		return x.ServerListenAddr
	}
	return ""
}

func (x *ServerInfo) GetClientListenAddr() string {
	if x != nil {
		return x.ClientListenAddr
	}
	return ""
}

func (x *ServerInfo) GetWsClientListenAddr() string {
	if x != nil {
		return x.WsClientListenAddr
	}
	return ""
}

func (x *ServerInfo) GetGateListenAddr() string {
	if x != nil {
		return x.GateListenAddr
	}
	return ""
}

func (x *ServerInfo) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

func (x *ServerInfo) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

// 踢玩家下线req
type KickPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"` // 账号id
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`   // 玩家id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerReq) Reset() {
	*x = KickPlayerReq{}
	mi := &file_server_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerReq) ProtoMessage() {}

func (x *KickPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerReq.ProtoReflect.Descriptor instead.
func (*KickPlayerReq) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{1}
}

func (x *KickPlayerReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *KickPlayerReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 踢玩家下线res
type KickPlayerRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"` // 账号id
	PlayerId      int64                  `protobuf:"varint,3,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`   // 玩家id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerRes) Reset() {
	*x = KickPlayerRes{}
	mi := &file_server_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRes) ProtoMessage() {}

func (x *KickPlayerRes) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRes.ProtoReflect.Descriptor instead.
func (*KickPlayerRes) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{2}
}

func (x *KickPlayerRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *KickPlayerRes) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *KickPlayerRes) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 客户端掉线
type ClientDisconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientConnId  uint32                 `protobuf:"varint,1,opt,name=ClientConnId,proto3" json:"ClientConnId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDisconnect) Reset() {
	*x = ClientDisconnect{}
	mi := &file_server_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnect) ProtoMessage() {}

func (x *ClientDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnect.ProtoReflect.Descriptor instead.
func (*ClientDisconnect) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{3}
}

func (x *ClientDisconnect) GetClientConnId() uint32 {
	if x != nil {
		return x.ClientConnId
	}
	return 0
}

// 服务器连接上其他服务器时,发的初始化信息
type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`    // 服务器id
	ServerType    string                 `protobuf:"bytes,2,opt,name=ServerType,proto3" json:"ServerType,omitempty"` // 服务器类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_server_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_server_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_server_base_proto_rawDescGZIP(), []int{4}
}

func (x *ServerHello) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerHello) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

var File_server_base_proto protoreflect.FileDescriptor

const file_server_base_proto_rawDesc = "" +
	"\n" +
	"\x11server_base.proto\x12\agserver\"\xb4\x02\n" +
	"\n" +
	"ServerInfo\x12\x1a\n" +
	"\bServerId\x18\x01 \x01(\x05R\bServerId\x12\x1e\n" +
	"\n" +
	"ServerType\x18\x02 \x01(\tR\n" +
	"ServerType\x12*\n" +
	"\x10ServerListenAddr\x18\x03 \x01(\tR\x10ServerListenAddr\x12*\n" +
	"\x10ClientListenAddr\x18\x04 \x01(\tR\x10ClientListenAddr\x12.\n" +
	"\x12WsClientListenAddr\x18\x05 \x01(\tR\x12WsClientListenAddr\x12&\n" +
	"\x0eGateListenAddr\x18\x06 \x01(\tR\x0eGateListenAddr\x12&\n" +
	"\x0eLastActiveTime\x18\a \x01(\x03R\x0eLastActiveTime\x12\x12\n" +
	"\x04Ping\x18\b \x01(\x05R\x04Ping\"I\n" +
	"\rKickPlayerReq\x12\x1c\n" +
	"\tAccountId\x18\x01 \x01(\x03R\tAccountId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\"_\n" +
	"\rKickPlayerRes\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\x03R\tAccountId\x12\x1a\n" +
	"\bPlayerId\x18\x03 \x01(\x03R\bPlayerId\"6\n" +
	"\x10ClientDisconnect\x12\"\n" +
	"\fClientConnId\x18\x01 \x01(\rR\fClientConnId\"I\n" +
	"\vServerHello\x12\x1a\n" +
	"\bServerId\x18\x01 \x01(\x05R\bServerId\x12\x1e\n" +
	"\n" +
	"ServerType\x18\x02 \x01(\tR\n" +
	"ServerTypeB\x06Z\x04./pbb\x06proto3"

var (
	file_server_base_proto_rawDescOnce sync.Once
	file_server_base_proto_rawDescData []byte
)

func file_server_base_proto_rawDescGZIP() []byte {
	file_server_base_proto_rawDescOnce.Do(func() {
		file_server_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_base_proto_rawDesc), len(file_server_base_proto_rawDesc)))
	})
	return file_server_base_proto_rawDescData
}

var file_server_base_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_server_base_proto_goTypes = []any{
	(*ServerInfo)(nil),       // 0: gserver.ServerInfo
	(*KickPlayerReq)(nil),    // 1: gserver.KickPlayerReq
	(*KickPlayerRes)(nil),    // 2: gserver.KickPlayerRes
	(*ClientDisconnect)(nil), // 3: gserver.ClientDisconnect
	(*ServerHello)(nil),      // 4: gserver.ServerHello
}
var file_server_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_base_proto_init() }
func file_server_base_proto_init() {
	if File_server_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_base_proto_rawDesc), len(file_server_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_base_proto_goTypes,
		DependencyIndexes: file_server_base_proto_depIdxs,
		MessageInfos:      file_server_base_proto_msgTypes,
	}.Build()
	File_server_base_proto = out.File
	file_server_base_proto_goTypes = nil
	file_server_base_proto_depIdxs = nil
}
