#服务器进程唯一id
ServerId: 102
#监听客户端
Client:
  Addr: :10201
#监听网关
Gate:
  Addr: :10202
#监听其他服务器
Server:
  Addr: :10203
#数据库
Mongo:
  Uri: mongodb://127.0.0.1:27017
  Db: testdb
#缓存
Redis:
  Uri:
    - 127.0.0.1:6379
  UserName:
  Password:
  Cluster: false
#是否测试环境(测试环境开启;生产环境必须为false或不配置,防止正式服作弊)
IsTestEnv: true